### ISSUE TITLE
Greedy Timers

### ISSUE THREAD

**Issue by daanzu** [dictation-toolbox/dragonfly#109]
Currently, if a Timer falls behind in getting called, it can start monopolizing execution. This is a valid option for the wary user, but seems a dangerous default.

It'd be safer to reset the next time to from now. Perhaps with a warning that calls were skipped.

https://github.com/dictation-toolbox/dragonfly/blob/e50b0006e1b4ab45ad4413f362c85c57ff9dfc60/dragonfly/engines/base/timer.py#L89

**Comment by Danesprite** [comment]
Sounds like a good idea to me. So it should be something like `self.next_time = time.time() + self.interval` instead?

**Comment by daanzu** [comment]
Yes. I wonder whether to put in a option for it, or adding a warning when a timer call is late, but a timer that cares that much about it should probably just track it itself?

**Comment by Danesprite** [comment]
I'd say just log an *INFO* message. If a timer cares that much, then yes it should just keep track of that.

**Comment by daanzu** [comment]
Want me to submit a PR?

**Comment by Danesprite** [comment]
Sure! I would have done it earlier, just been a little busy!

**Comment by daanzu** [comment]
Ha, no problem, I will send one in this evening.

**Comment by daanzu** [comment]
Fixed in #119
