### ISSUE TITLE
No handlers could be found for logger "typeables"

### ISSUE THREAD

**Issue by MatthijsBurgh** [dictation-toolbox/dragonfly#115]
When importing dragonfly I get the following logging message:
```
No handlers could be found for logger "typeables"
Falling back to Shift+insert for Paste's action.
```
If I execute the following lines before importing dragonfly, I don't get this message.
```
import logging
logging.basicConfig()
```
I suggest to add the `logging.basicConfig()` in the `actions/typeables.py` directly after importing `logging`.

If you agree, I can create a PR for you.

**Comment by Danesprite** [comment]
Thanks. It looks like calling `logging.basicConfig()` in `dragonfly/__init__.py` should fix this and other similar issues. I'll do that and also fix some other logging issues.
