### ISSUE TITLE
Constructing grammars with elements don't work and are poorly documented

### ISSUE THREAD

**Issue by TMiguelT** [dictation-toolbox/dragonfly#142]
I'm finding this very confusing. The [documentation](https://dragonfly2.readthedocs.io/en/latest/object_model.html) goes on at length about the Object Model, in which grammars are made up of rules, which are made up of elements. However, not a single Dragonfly grammar I've ever seen constructs grammars this way. They all use `MappingRule` or `CompoundRule` to write their grammars using strings. 

I didn't much like that approach, so I tried making a simple grammar using elements, but it fails to be recognized by the Kaldi engine:

```python
import dragonfly

letter_el = dragonfly.Alternative([dragonfly.Literal(l) for l in string.ascii_lowercase])
letters_el = dragonfly.Repetition(letter_el, min=1, max=2)
jump_to = dragonfly.Grammar('jump_to')
jump_to.add_rule(dragonfly.Rule(element=letters_el))
jump_to.load()
```
Is there something fundamental I'm missing here? The grammar should recognize combinations of 1-2 letters, like "a", "bc", "zc" etc.

The issue with documentation that I have is that there aren't actually any examples of a whole grammar made up only of `Element` subclasses. The only two example grammars I could find used a [`CompoundRule`](https://dragonfly2.readthedocs.io/en/latest/rules.html#example-usage) and a [`MappingRule`](https://dragonfly2.readthedocs.io/en/latest/rules.html#id1) as mentioned above. This is awfully confusing to newcomers. If direct `Element` use is deprecated, I think the `Compound` grammar should be documented and shown much before any talk about the object model.

**Comment by daanzu** [comment]
I believe `Rule` is an abstract base class, not intended to be used directly, because its `process_recognition` method is left blank. A good minimum for what you want is probably simply:

```
class SimpleKeyboardRule(CompoundRule):
    spec = "<simple_keyboard_sequence>"
    extras = [simple_keyboard_sequence]
    def _process_recognition(self, node, extras):
        sequence = extras["simple_keyboard_sequence"]
        for action in flatten(sequence):
            action.execute()
```

**Comment by TMiguelT** [comment]
Is it not possible to formulate a grammar without using a `CompoundRule`? This seems very strange

**Comment by daanzu** [comment]
I think that and MappingRule are the two included concrete implementations.

**Comment by daanzu** [comment]
It is probably a good idea to add a `SimpleRule` like the above to the library.

**Comment by TMiguelT** [comment]
Ohhh, that explains my confusion. But that's very strange if it's true. Because that means that you can't bypass the `spec` string parsing. Surely there must be some way to combine elements directly into a rule without using a string `spec`?

**Comment by mrob95** [comment]
The reason why every user facing rule uses `Compound` elements is because this is the only way (I think) of mapping string commands to values to be acted on e.g.:

```
Compound("some command", value=Text("some action"))
```

If you want to get all of the functionality of a mapping rule using individual elements then I think you'll need something like:

```
from dragonfly import Compound as CompoundBase


class BoundCompound(CompoundBase):

    def value(self, node):
        extras = {"_node": node}
        for name, element in self._extras.items():
            extra_node = node.get_child_by_name(name, shallow=True)
            if extra_node:
                extras[name] = extra_node.value()
            elif element.has_default():
                extras[name] = element.default
        if self._value is not None:
            return self._value.copy_bind(extras)
```
and
```
class BasicRule(Rule):

    def process_recognition(self, node):
        value = node.value()
        if isinstance(value, list):
            for action in node.value():
                action.execute()
        else:
            value.execute()
```

This should allow you to build up rules like:
```
rule1 = BasicRule(
    "rule1",
    Repetition(
        Alternative((
            Compound("test one", value=Text("1")),
            Compound("test two", value=Text("2")),
            Compound("test three", value=Text("3")),
        )),
        1, 5
    ),
    context=None,
    exported=True
)
```


Maybe something like this should be added? The reason you have to override compound is because at the moment binding the value of a recognised compound element with the values of the extras that were also recognised is done by the mapping rule, which doesn't really make much sense to me unless I am missing something.

**Comment by daanzu** [comment]
Ah, I always forget that `Rule` has default `exported=False`. Probably because it is an abstract base class and not meant to be used directly.

**Comment by daanzu** [comment]
By the way, I'm putting together a PR for this.

**Comment by TMiguelT** [comment]
I like the idea of a `BasicRule` that has a single base element and is exported by default:

```python
class JumpRule(dragonfly.Rule):
    element = dragonfly.Repetition(
        dragonfly.Alternative([dragonfly.Literal(l) for l in string.ascii_lowercase]),
        min=1,
        max=2
    )

    def _process_recognition(node):
        # do something using `node`
```

But simply adding `exported=True` is satisfying enough for me.

Also, as I was kind of getting at, I think the documentation could do with some good examples for this, and for `CompoundRule`s (is the `spec` grammar documented anywhere?)

**Comment by Danesprite** [comment]
I agree that this part of Dragonfly is poorly documented and clearly wasn't designed to be used directly. I think adding a `BasicRule` class is a great idea.

Compound specs aren't documented properly either, just the examples on the [rules page](https://dragonfly2.readthedocs.io/en/latest/rules.html). The `Compound` class's documentation should specify what is accepted by its parser. That could be referenced to in the docstrings for `MappingRule` and `CompoundRule`.

**Comment by mrob95** [comment]
On a slightly related note. Do you think dragonfly should offer an implementation of CCR? It's probably a feature that the vast majority of users want for most of their commands, but at the moment we don't really offer any guidance or examples of how to do it well.

**Comment by daanzu** [comment]
Re CCR: Do you mean just an easier interface to `Repetition`?

**Comment by mrob95** [comment]
Kind of, but the desired behaviour is something like "all of the rules I have added which match the current context are active, and I can say any of them in any order as many times as I want".

**Comment by Danesprite** [comment]
This has come up before. There is a documentation section on CCR: https://dragonfly2.readthedocs.io/en/latest/ccr.html

I'm not willing to maintain something like Caster's CCR merger or Dragonfluid's `FluidRule` within Dragonfly. One thing we could do is add a modified version of the `SeriesMappingRule` class used in [dragonfly-scripts](https://github.com/dictation-toolbox/dragonfly-scripts/). That would at least be easier than using `Repetition` directly.

**Comment by daanzu** [comment]
Hmm, yeah, supporting that in dragonfly seems like a big addition. However, I need to think about it a bit more, but supporting that easily just in the Kaldi backend might not be hard at all.

**Comment by Danesprite** [comment]
Yeah, it's a bit much.

Supporting that in the Kaldi backend would be interesting. I guess it could be done with optional attribute(s) on `Grammar` and `Rule` objects like what you've done recently with the optional `weight` attribute.

**Comment by mrob95** [comment]
FYI I'm working on this at the moment as a separate project - essentially a command definition API with automatic CCR. I think it's possible in a way that isn't totally horrible. We'll see!

**Comment by Danesprite** [comment]
Oh cool! That sounds interesting :+1:

**Comment by daanzu** [comment]
@mrob95 Very interested to see it!

**Comment by Danesprite** [comment]
I'm reopening this because this could still be documented a little better. You also you wouldn't be able to use the base `Rule` class as above:
```Python
class JumpRule(dragonfly.BasicRule):
    element = dragonfly.Repetition(
        dragonfly.Alternative([dragonfly.Literal(l) for l in string.ascii_lowercase]),
        min=1,
        max=2
    )

    def _process_recognition(node):
        # do something using `node`
```

Defining the `element`, `name`, `context`, `imported` and/or `exported` parameters on the class-level won't currently work like they do with the `CompoundRule` and `MappingRule` classes.

**Comment by Danesprite** [comment]
@mrob95 Would you be okay with your `BoundCompound` and `BasicRule` classes posted above being added to Dragonfly to make it easier to construct grammars with elements?

**Comment by mrob95** [comment]
Of course! Would be a nice simplification in Breathe to be able to remove them. The code for binding extras was mostly taken from MappingRule so you might be able to reduce complexity there if it can all be done in the Compound.

**Comment by Danesprite** [comment]
Great! I'll open a new pull request for adding them in the next release version. I will look into reducing the complexity of the binding extras code.
