### ISSUE TITLE
wav decoding kaldi

### ISSUE THREAD

**Issue by yondu22** [dictation-toolbox/dragonfly#160]
Is there any example of how to to do file based decoding with kaldi engine?

**Comment by Danesprite** [comment]
No, this isn't possible with Kaldi at the moment, but I don' t think it should be difficult to implement.

@daanzu What do you think? Could this be done, perhaps by re-using the Sphinx engine's [`process_wave_file()`](https://github.com/dictation-toolbox/dragonfly/blob/master/dragonfly/engines/backend_sphinx/engine.py#L894) method somehow?

**Comment by daanzu** [comment]
I definitely intend to implement decoding from wave files, particularly to do full automated integration testing. I will try to get it done soon.

**Comment by Danesprite** [comment]
That would be a good use for wave file decoding. I wonder if implementing this could be done as part of unifying the audio code for the Kaldi, Sphinx and Silvius/VoxHub engines. We talked about that a while ago on one of the Gitter channels.

**Comment by daanzu** [comment]
This is implemented in #175 with `KaldiEngine.recognize_wave_file()`.

**Comment by Danesprite** [comment]
Dragonfly2 version 0.19.0 includes the new `recognize_wave_file()` method. I'm closing this as resolved now.
