### ISSUE TITLE
Mouse clicks don't account for Windows 10 primary mouse button assignment

### ISSUE THREAD

**Issue by zilch42** [dictation-toolbox/dragonfly#185]
I mostly use a left-handed mouse because my main issue is with my right hand, and I just realised that Caster's mouse click rules don't account for Windows 10's primary mouse button settings. 

I.e. if your primary mouse button is set to "Right" in Window's settings, "Kick" gives you a right click rather than a left click and "Psychic" gives you the opposite as well. 

It would be great if those left and right click rules could be assigned to primary and secondary mouse clicks, rather than literal left and right mouse clicks.

**Comment by Danesprite** [comment]
@LexiconCode No worries. You need to use `SwapMouseButton()` via `ctypes.windll` BTW; `Pywin32` doesn't include it.

I think it's debatable whether or not this is a bug. I wouldn't expect *simulated* mouse events for the left and right buttons to be effected by Windows' primary mouse button setting. That's assuming device drivers don't use `SendInput()` too, I don't know how that all works.
