### ISSUE TITLE
Importing the win32ui module crashes Natlink if used out of process

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/dragonfly#205]
Simply importing `win32ui` crashes Natlink if used out of process. The issue does not occur when using in process method through Natlinks GUI. The crash manifests itself through an absence of recognition through Dragon and natlink's waitForSpeech gui freezes. Ultimately natlink's process has to be ended using to the task manager. After the process is terminated DNS resumes recognition.

To reproduce
1. Use latest dragonfly master branch
2. load grammar with natlink out of process `python -m dragonfly load --engine natlink _testnatlink.py`
3. Say `test function`

```
from dragonfly import Text, Function, MappingRule, Grammar

# Out of process Natlink test

def import_win32ui():
    try:
        import win32ui
    except Exception as e:
        print(e)


class BasicRule(MappingRule):
    mapping = {
        "test function": Function(import_win32ui),
        "test text": Text("testing text success"),
    }
    extras = [
        
    ]

basic_grammar = Grammar("basic rule")
basic_grammar.add_rule(BasicRule())
basic_grammar.load()
```

**Comment by Danesprite** [comment]
@LexiconCode Should this issue be documented in the [FAQ](https://dragonfly2.readthedocs.io/en/latest/faq.html), perhaps along with the other unfortunate limitations with running Python code with Natlink?

**Comment by LexiconCode** [comment]
I think that would be appropriate place.

**Comment by Danesprite** [comment]
Okay. I'll add a question and answer into the FAQ. Something like "Why doesn't multi-threaded or GUI code work when using Dragon and Natlink?"

**Comment by Danesprite** [comment]
I added two questions on GUI and threading code to the FAQ in #232. I've referenced this issue from one of them.
