### ISSUE TITLE
Add the latest version of Dragon software that dragonfly will work with in the documentation

### ISSUE THREAD

**Issue by AcademyOfF** [dictation-toolbox/dragonfly#207]
Whenever I Google about programming with Dragon software, there's always something saying that software only works with an old version, like Dragon 12. The latest version of Dragon software is 15. Does dragonfly work with the latest version? Regardless, I think it's worth mentioning the latest version dragonfly Is known to work with in the documentation.

**Comment by LexiconCode** [comment]
Yes there's lots of outdated information out there. To let you know it works with Dragon 13 through 15. Possibly even 12 through but I can't recall.

**Comment by Danesprite** [comment]
As far as I know, the latest versions of Natlink and Dragonfly2 work with Dragon versions 10 to 15. I'll add the supported versions into the documentation and the `README` file.
