### ISSUE TITLE
Dragonfly Execution of Key TypeError python 3

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/dragonfly#216]
This is a bug in Python 3.8.2 with Dragonfly `set_foreground`
```
ERROR:action.exec:Execution of Key('control:down,control:up') failed due to exception: argument 2: <class 'TypeError'>: expected LP_INPUT instance instead of LP__Input_Array_2
Traceback (most recent call last):
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dragonfly\actions\action_base.py", line 97, in execute
    if self._execute(data) is False:
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dragonfly\actions\action_base_keyboard.py", line 131, in _execute
    return super(BaseKeyboardAction, self)._execute(data)
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dragonfly\actions\action_base.py", line 153, in _execute
    self._execute_events(self._events)
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dragonfly\actions\action_key.py", line 513, in _execute_events
    self._keyboard.send_keyboard_events(events)
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dragonfly\actions\keyboard\_win32.py", line 277, in send_keyboard_events
    send_input_array(array)
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dragonfly\actions\sendinput.py", line 170, in send_input_array
    count_inserted = windll.user32.SendInput(length, ptr, size)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: expected LP_INPUT instance instead of LP__Input_Array_2
```

**Comment by LexiconCode** [comment]
Actually it's a conflict between pynput and ctypes.

https://stackoverflow.com/questions/53643273/how-to-keep-pynput-and-ctypes-from-clashing

**Comment by Danesprite** [comment]
Thanks for opening this. I've come across this problem before and wondered whether it was worth making an issue on. The problem, as you've discovered, is that Dragonfly doesn't set `SendInput.argtypes`, but pynput [does](https://github.com/moses-palmer/pynput/blob/d5db66dc22a6a856657a75c18cb853356512136c/lib/pynput/_util/win32.py#L129). This makes the `SendInput` function break when we use it in Dragonfly. As such, I would consider this an external bug.

I can't imagine this problem would prop up much really; Dragonfly does most of what pynput does already. I'd like to mention @moses-palmer anyway so they are aware of the problem.

Removing the following lines from `pynput._util.win32` makes both libraries cooperate for me:

```Python
SendInput.argtypes = (
    wintypes.UINT,
    LPINPUT,
    ctypes.c_int)

```

I'm certain this problem would occur with other `windll` functions that both libraries use. I would be curious as to whether there is some benefit to doing this, it doesn't seem to be required.

We can also fix this from Dragonfly by setting `SendInput.argtypes` to `None`.

**Comment by moses-palmer** [comment]
Thanks for the mention. The added type signatures in *pynput* are mostly for documentation, so I will look into whether removing them is possible.

**Comment by moses-palmer** [comment]
The *master* branch of *pynput* now contains a presumed fix for this.

It unfortunately proved impossible to remove the `argtypes` specifications---the `int`s were incompatible in my test system---but *pynput* no longer specifies internal types, but rather `ctypes.c_voidp`, which should be compatible with whatever is passed to the functions from *dragonfly*.

**Comment by Danesprite** [comment]
No worries about the mention.

I have tested using *dragonfly* with the master branch version of *pynput* and the libraries are now indeed compatible and working nicely together. You didn't need to fix this problem so promptly, so thank you! :-)
