### ISSUE TITLE
Verify Natlink on Python path when launching out of process

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/dragonfly#222]
Natlink 4.2 is supposed to add itself to the Python path via the registry. On a rare occasion for some users this fails.

From the end-user's perspective
1. They have Python version 2.7.17 32-bit including the option to put Python in the path.
2. Downloaded and installed Natlink 4.2.
3. run `python -m dragonfly load --engine natlink _*.py --no-recobs-messages`
4. See the error message below

```
WARNING:engine.natlink:Requested engine 'natlink' is not available: Natlink is n
ot installed: No module named natlink
ERROR:command:Requested engine 'natlink' not available.
```

Ideally this will be resolved in Natlink py3 port. For now Natlink 4.2
adding `MacroSystem\core` to `sys.path` should resolve the issue.
```Python
try:
    import natlink
except ImportError:
    coredir = 'C:\\NatLink\\NatLink\\MacroSystem\\core'
    if os.path.isdir(coredir):
        sys.path.append(coredir)
    import natlink
except ImportError as e:
	_log.warning("Requested engine 'natlink' is not available: Natlink "
                "is not installed: %s", e)
```

The above is pseudocode as there must be a better way for error handling besides a double `except ImportError`.

**Comment by LexiconCode** [comment]
I've made a test script to help people troubleshoot and test the suggested fix above.

```Python
from __future__ import print_function 
import os, sys

try:
    import natlink
    print("Natlink successfully imported!")
except ImportError:
    # Adjust coredir path if necessary to NatLink core Directory
    coredir = 'C:\\NatLink\\NatLink\\MacroSystem\\core'
    if os.path.isdir(coredir):
        print("Attempting to temporarily add Natlink to path: " + coredir)
        sys.path.append(coredir)
    else:
        print("Natlink path does not exist: "  + coredir)
    try:
        import natlink
    except ImportError as e:
        print("\n Natlink failed to import!: %s", e)
finally:
    print("\n Debugging: Printing out everything on Python Path (sys.path): \n")
    print(*sys.path,sep='\n')
```

**Comment by LexiconCode** [comment]
Given that Natlink for Python 2.7 is end-of-life a fix like this does not need actualized in a merge. Good to have it referenced at least in an issue.

**Comment by Danesprite** [comment]
I wouldn't mind merging a fix for this. Even though Python 2.7 is end-of-life, it's safe to say most users of Dragonfly and Caster still use it.

**Comment by LexiconCode** [comment]
> 
> 
> I wouldn't mind merging a fix for this. Even though Python 2.7 is end-of-life, it's safe to say most users of Dragonfly and Caster still use it.

Okay that sounds like a plan. I'll see what I can come up with. The implementation will be be similar but it'll check the python path first for `...NatLink\\MacroSystem\\core` and verify `natlink.pyd` is in `core`. (import natlink)

**Comment by Danesprite** [comment]
Okay then :+1:. I don't mind just adding your fix in a new PR
