### ISSUE TITLE
Triple Monitor - Unable To Move Mouse To Left Monitor

### ISSUE THREAD

**Issue by MarkRx** [dictation-toolbox/dragonfly#228]
In a triple monitor setup dragonfly.monitors is reporting the x coordinate of my left monitor as being negative. The Mouse command treats a negative value as an offset from the right edge. It thus seems the monitor coordinate system is different than the one that the Mouse action uses. I am not able to get the Mouse command to move the mouse to my left monitor because of it.

I suspect you can reproduce by putting a second monitor on the left of your primary monitor thus giving it a negative x coordinate. I have put a code snippet below that will reproduce the issue (on my machine at least).

## Setup
Windows 10
Left Monitor 1920x1080 (Per Windows): 2
Center Monitor 1920x1080 (Per Windows): 3
Right Monitor 1920x1080 (Per Windows): 1

The center monitor is my main display in Windows

![image](https://user-images.githubusercontent.com/17504314/77807480-54ca4400-705e-11ea-8104-7f28ba9a880e.png)

dragonfly.monitors:
Left Monitor (Per dragonfly): 1 (0-based)
Center Monitor (Per dragonfly): 0 (0-based)
Right Monitor (Per dragonfly): 2 (0-based)

## Expected
I can use a Mouse command to move the mouse to my left monitor (neither `Mouse("[-960, 540]").execute()` nor `Mouse("[4800, 540]").execute()` work)

## Actual
I am unable to use the mouse command to access my left monitor.

## Code
```
from time import sleep

from dragonfly import monitors, Mouse

for num, mon in enumerate(monitors):
    r = mon.rectangle
    print("Monitor {} Dimensions: x: {} y: {} w: {} h: {}".format(num, r.x, r.y, r.dx, r.dy))

print("Move to left screen?")
# This command ends up putting the mouse on my center screen which per documentation I think is expected
Mouse("[-960, 540]").execute()
sleep(2)

print("Move to left screen?")
# This command ends up putting the mouse on my center screen - seems to wrap
Mouse("[4800, 540]").execute()
sleep(2)

print("Move to center screen")
Mouse("[960, 540]").execute()
sleep(2)

print("Move to right screen")
Mouse("[2880, 540]").execute()
sleep(2)

# There is no way to put the mouse on my left screen
```

## Output

> Monitor 0 Dimensions: x: 0.0 y: 0.0 w: 1920.0 h: 1080.0
> Monitor 1 Dimensions: x: -1920.0 y: 0.0 w: 1920.0 h: 1080.0
> Monitor 2 Dimensions: x: 1920.0 y: 0.0 w: 1920.0 h: 1080.0
> Move to left screen
> Move to center screen
> Move to right screen

**Comment by Danesprite** [comment]
Thanks for reporting this bug and including all this detailed information! I'm fairly certain I know what's causing the problem. I'll see if I can fix it today or tomorrow.

**Comment by MarkRx** [comment]
See https://github.com/dictation-toolbox/dragonfly/pull/230#issuecomment-605702887
