### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by Danesprite** [dictation-toolbox/dragonfly#255]
CC @droundy, @TMiguelT

Wayland is an alternative to the X11 protocol used for desktop environments on Linux and other systems. It is intended to replace X11.

In my view, Wayland is not ready for those who depend on accessibility software like Dragonfly because it doesn't directly support the following:
* simulated keyboard/mouse input
* ability to inspect window attributes (e.g. window title, executable and handle)
* ability to manipulate windows (e.g. maximise, close, etc)

It is possible to have limited `Key`, `Text` and `Mouse` action support is via [python-evdev](https://github.com/gvalkov/python-evdev) or similar. This skips Wayland entirely and is discussed in [issue #8](https://github.com/dictation-toolbox/dragonfly/issues/8) in detail. I believe this is the best we can do at the moment.

Functionality utilising Dragonfly's [`Window` class](https://dragonfly2.readthedocs.io/en/latest/window_classes.html), such as `AppContext`, will not be functional under Wayland.

I suspect that one or more Wayland compositors could in the future expose the accessibility APIs we need for keyboard/mouse input and window inspection/management. Unfortunately, as these would have to be Wayland extensions, Dragonfly would probably need different implementations for each compositor. There are currently 10 different Wayland display servers [listed here](https://en.wikipedia.org/wiki/List_of_display_servers#Wayland), so I'd like to suggest that we rule out having implementations for APIs specific to certain Wayland compositors because it would involve considerable maintenance and is more suited to a separate, dedicated project.

**Comment by droundy** [comment]
I came across [ydotool](https://github.com/ReimuNotMoe/ydotool) which seems to address some of the Wayland issues.

**Comment by Danesprite** [comment]
Yes, ydotool looks good. The only problem is that evdev normally requires the process to run as root. Ydotool does have a daemon component that might be used to work around that problem. I'll see if I can get that working and report back.

**Comment by Danesprite** [comment]
I haven't been able to successfully test Ydotool on my machine. Aenea has a workable server implementation for use on Wayland that I know works properly: https://github.com/dictation-toolbox/aenea/tree/master/server/linux_wayland

I just want to say here that I cannot commit to working on this myself.

**Comment by maricn** [comment]
`ydotool` is problematic with typing (unicode) characters that are not found on US keyboard https://github.com/ReimuNotMoe/ydotool/issues/9 (or more precisely in https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h)

I personally use https://gitlab.com/interception/linux/tools/ which are also based on creating virtual `libudev` devices to simulate input devices.

Haven't used `python-evdev` but it seems like all three mentioned would suffer from the same problem. Just something to note here. I don't have a suggestion to mitigate that.

Looking forward to wayland support anyways.

**Comment by Danesprite** [comment]
Hello @maricn,

Thanks for mentioning these things. The Linux interception tools do look promising. I will try to test them soon. It would be nice if they were easily installable on Debian-based systems.

**Comment by LexiconCode** [comment]
Things that look promising [wlrctl](https://git.sr.ht/~brocellous/wlrctl) / [wlroots](https://github.com/swaywm/wlroots)/[wlr-protocols](https://github.com/swaywm/wlr-protocols)

> simulated keyboard/mouse input possible on wlroots compositor with wlrctl


> ability to inspect window attributes (e.g. window title, executable and handle)


the foreign-toplevel-manager protocol addresses that to an extent. It's used for taskbars. see wlr-protocols


> Ability to manipulate windows (e.g. maximise, close, etc) - Programmatically control window functions.

you can also use wlrctl for that.

So my thought is if these can provide basic functionality. Whereas compositor display servers geared towards advanced usage. [wayfire](https://github.com/WayfireWM/wayfire), perhaps we should select the distro or to with waland as default and only support those without direct community contributions. Debian and Ubuntu with GNOME 
https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-21.04-Wayland-Default

**Comment by tom-james-watson** [comment]
Note - wlrctl for simulated keyboard only supports ascii.

**Comment by LexiconCode** [comment]
I think there also be some limitations with window tile managers which don't have the concept of minimize and maximize as such for example `sway`.

Underneath it although I don't think there's a way at getting at what we need without root access. Compositors are unlikely to provide privileged access to an unprivileged process. So possibly we need to have some sort of daemon process that has elevated privileges the dragonfly(unprivileged) has access to but limited scope.

My thoughts regarding daemon Was based on [gnome-ponytail-daemon](https://gitlab.gnome.org/ofourdan/gnome-ponytail-daemon)

**Comment by Danesprite** [comment]
> I think there also be some limitations with window tile managers which don't have the concept of minimize and maximize as such for example `sway`.

Yes, that is correct.  Tiling window managers are actually quite old.  According to [the Wikipedia article on them](https://en.wikipedia.org/wiki/Tiling_window_manager), they date back to the 1980s.  Microsoft Windows 1.0 used tiling, for example.  You can still use it from the taskbar actually.  :-)

> Underneath it although I don't think there's a way at getting at what we need without root access.

Agreed.  This is one barrier to partial Wayland support.

> Compositors are unlikely to provide privileged access to an unprivileged process. So possibly we need to have some sort of daemon process that has elevated privileges the dragonfly(unprivileged) has access to but limited scope.

In my opinion, this is something that should be covered by Wayland itself in a core component shared by all compositors.  After all, they were the ones that left out the relevant X11 APIs on security grounds.

I would be against supporting particular compositors or desktop environments as it would be a lot of work for little to no benefit.  Requiring every Wayland compositor to implement these things is, in my view, bad software engineering practice.  I am no expert on this, but I am led to believe that X11 has major problems which Wayland solves.  This is no reason to throw out what works.

Having given it further thought, I have come to the conclusion that using the Linux interception tools mentioned above by @maricn would not be an acceptable solution either, since this would be a partial, Linux-only solution to the problem.  Dragonfly's core assistive functionality supports Windows, macOS and (Xorg) *X11*, which works on UNIX and UNIX-like systems, not *only* Linux.

At this point, I would still simply recommend any Wayland users switch to X11. Failing that, Windows and macOS are far better supported.  Until there are developments in the direction of unified Wayland APIs providing the same functionality present under X11, I consider to be Wayland **unsupportable** and will be closing this issue.

My apologies for taking a few months to reply to these posts!

**Comment by LexiconCode** [comment]
It might be possible to support this in the future once the fragmentation of wayland compositors consolidate. A few helpful resources for understanding what protocols are implemented and equivalents with X11. I will update this post if I find anything that tracks/implements compositors consolidation.

https://wayland-bites.github.io/#EWMH%20(NetWM)
https://wayland.app/protocols/

**Comment by Danesprite** [comment]
Thanks for the links, Aaron.  The first one is especially useful.  The *xdg-shell* "standard protocol extension" looks like the best one, although it is still missing quite a bit.

The designers of Wayland seem to be quite concerned with security.  Overly so, in my opinion.  It is interesting to note that OpenBSD, a UNIX-like operating system focused largely on security, still recommends X11 in their FAQ (see [p. 11](https://www.openbsd.org/faq/faq11.html)).  It looks like they don't have official packages for Wayland in version 6.9 (see the [packages list](https://cdn.openbsd.org/pub/OpenBSD/6.9/packages/amd64/)).  All this would seem to suggest that the issues solved by Wayland are overblown.  And even if they aren't, it isn't difficult to use X11 normally and swap to Wayland (or a separate X11 session) for "sensitive" work.

In any case, I plan to make it easier for users to implement and use custom platform code in the future.  I'm hoping the platform code can be refactored into one module per platform, putting aside certain modules like *sendinput.py*.  This is admittedly what I should have done originally.  I would be against merging a module for Wayland unless it covered most of our API surface.

**Comment by Danesprite** [comment]
I am considering new keyboard and mouse implementations for [dotool](https://git.sr.ht/~geb/dotool).  (See my comment in issue #374.)  This would enable keyboard and mouse control under Wayland on Linux.  The main reason for adding these, really, is that many Linux distributions now come with Wayland as the default display server.  Frankly, I think this was a mistake.  Wayland is half-baked and no substitute for X11.  Many programs that work under X11 do not work under Wayland.  But, since it is becoming somewhat standard, Dragonfly might as well have basic support for it.

As I understand it, in order for *dotool* to work after installation, the user need only be a member of the 'input' group.  This is a marked improvement over solutions requiring user code to run as root.  It will also apparently work in TTYs.

I remain opposed to compositor-specific implementations for Dragonfly features.  This will simply result in confused users.  They will ask questions like, "Why do my Firefox voice commands work in GNOME, but not in KDE?"  X11 is still a sound option that avoids such confusion.

I have changed on mind on making it easier for users to implement and use custom platform code.  This would be a big job with little payoff.

**Comment by Danesprite** [comment]
Having thought about this some more, I think it only makes sense for a library to offer "support" for a platform if most features actually work on it.  This library already has very good support for Windows, X11 and macOS.  That is quite enough, in my opinion.
