### ISSUE TITLE
nicer mechanism to select device in kaldi 

### ISSUE THREAD

**Issue by droundy** [dictation-toolbox/dragonfly#257]
I'd love to have an API for starting the kaldi engine that allows to select the device by its name.  Just adding a mechanism to obtain the portaudio device numbers and descriptions programmatically before starting up the engine would be awesome.  Then I could search through those text descriptions to find the USB microphone that I want to use.

**Comment by daanzu** [comment]
Good idea, I hadn't thought to add support for returning the list programmatically.

**Comment by dwks** [comment]
FWIW, this works:
https://github.com/dwks/silvius/blob/master/stream/list-mics.py

**Comment by droundy** [comment]
I wonder whether accepting a string argument `k` for the device (as an alternative to the integer argument) and then searching through the names would be acceptable it would be acceptable. I'm thinking of a `k in name[I]` sort of search.

**Comment by daanzu** [comment]
@droundy Definitely a good idea. I will try to add it soon.

**Comment by Danesprite** [comment]
I think this can be closed now that David has added a new `audio_input_device` argument taking device names and indices. It is available in dragonfly2 version 0.26.0 and documented in the [Engine Configuration](https://dragonfly2.readthedocs.io/en/latest/kaldi_engine.html#engine-configuration) section.

**Comment by droundy** [comment]
This works and looks good.  I have one additional (and related) feature request I'll file separately.
