### ISSUE TITLE
generate grammer documentation

### ISSUE THREAD

**Issue by droundy** [dictation-toolbox/dragonfly#259]
It would be lovely to be able to auto-generate documentation of the grammar.  It seems like at least in principle this should be possible, and would be really convenient, either when adopting (and learning) someone else's grammar, or when developing changes to the grammar.  I'm imagining something that generates markdown, html or latex.

**Comment by Danesprite** [comment]
I agree it would be nice to have this. I am familiar with the [Sphinx documentation generator](https://www.sphinx-doc.org/en/master/), which can generate HTML, LaTeX and other formats. Dragonfly's documentation uses a Sphinx extension ([sphinx-argparse](https://github.com/alex-rudakov/sphinx-argparse)) to [document CLI commands](https://dragonfly2.readthedocs.io/en/latest/cli.html). It should be possible to write a custom Sphinx extension to generate documentation for grammars and rules.

@LexiconCode I recall you have brought this sort of thing up before. Maybe you have done something like this with Caster's documentation?

**Comment by LexiconCode** [comment]
This would be an awesome feature to have. Generating documentation from grammars is not been implemented in caster. The challenges and so much generating docs it's more of extracting the information out of the grammar in a way that is useful.

As a side note in case dragonfly implements CCR in the future.  CCR adds a extra challenge of managing grammars. It's important to expose grammars before they become part of the CCR merged state. That would allow for displaying commands as individual grammars or generating grammar documentation.

In Caster we currently are working Working on the UI to display commands that are in grammars. This PR https://github.com/dictation-toolbox/dragonfly/pull/219 was meant to format action classes for visualization.


https://user-images.githubusercontent.com/103494/76157525-2c5bc380-610a-11ea-9e15-cf5071480e3b.png

So you can see the work that's been done in terms of displaying available commands which still has some challenges left to be solved.

![image](https://user-images.githubusercontent.com/24551569/83982144-aeb27a00-a8e9-11ea-9b9e-0eda2a8fecb3.png)
I need to check to see if that is the most recent representation of the PR in Caster.

The challenging bit is going to retrieve information that's hidden behind a Function.

**Comment by Danesprite** [comment]
Sorry for the late response!

Thanks for this very detailed post! The Caster command visualisation UI is very impressive. Given that you have already solved some issues you mentioned with this, it might be a good idea to see if I can get Sphinx building documentation from it somehow.

**Comment by daanzu** [comment]
> I think if dragonfly had its own version of `rdescript` that may be of help. That way if commands are self descriptive they can go without and if more description is needed include that within the grammar.

I think this makes a lot of sense. May be as simple as making it an optional argument to `ActionBase()`?

Regarding how to handle documenting helper functions, have you considered using their docstrings to describe what they are doing, and then displaying that?

**Comment by LexiconCode** [comment]
> Regarding how to handle documenting helper functions, have you considered using their docstrings to describe what they are doing, and then displaying that?

That's an interesting thought! In terms of space not sure how that would fit on the GUI depending on the doc string. Perhaps the command could unfold with the doc string.

**Comment by Danesprite** [comment]
Documenting grammars or command modules can already be done with the [Configuration Toolkit](https://dragonfly2.readthedocs.io/en/latest/config.html).  Christo Butcher, the author of Dragonfly, wrote in his [dragonfly-modules](https://github.com/t4ngo/dragonfly-modules) repository many command modules and *.txt* files using this toolkit.

The following is an example configuration for commands that type letters A, B, C and numbers 1, 2, 3.

```Python
from dragonfly import Config, Section, Item

config                     = Config("Configuration")
config.cmd                 = Section("Command section")
config.cmd.type_letter     = Item("<letter>", doc="Type the <letter> key.")
config.cmd.type_number     = Item("<letter>", doc="Type the <number> key.")

config.extras              = Section("Command extras section")

config.extras.letter       = Section("Extra letter section")
config.extras.letter.a     = Item("alpha", doc="Letter A.")
config.extras.letter.b     = Item("bravo", doc="Letter B.")
config.extras.letter.c     = Item("charlie", doc="Letter C.")

config.extras.number       = Section("Extra number section")
config.extras.number.one   = Item("one", doc="Number 1.")
config.extras.number.two   = Item("two", doc="Number 2.")
config.extras.number.three = Item("three", doc="Number 3.")

```

By default, invoking [`Config.generate_config_file()`](https://dragonfly2.readthedocs.io/en/latest/config.html#dragonfly.config.Config.generate_config_file) results in a neatly formatted text document like [this one](https://github.com/t4ngo/dragonfly-modules/blob/master/command-modules/_audacity-en.txt).  Custom `Config` subclasses could be written to output information in different formats.

A `Config` hierarchy like the above could be generated from grammar, rule or element objects.  Using the above example, `Item` objects for each letter could be generated from the relevant `dict` object:

```Python
letter_names = {
    "Alpha":     "a",
    "Bravo":     "b",
    "Charlie":   "c",
    "Delta":     "d",
    "Echo":      "e",
    "Foxtrot":   "f",
    # Et cetera.
}

for k, v in letter_names.items():
    item = Item(k, doc="Letter %s." % v.upper())
    # config.extras.letter.<v> = item
    setattr(config.extras.letter, v, item)

```

The only thing missing here, in my opinion, is a method for outputting code similar to that in my first code block above.  With that added, one could do the following:
1. Create `Config`, `Section` and `Item` objects with data from a current grammar, using code similar to my second code block.
2. Generate clean configuration toolkit code and copy it back into the grammar file(s).
3. Replace strings in the grammar file(s) with items, e.g. `"alpha": "a"` becomes `config.extras.letter.a: "a"`.
4. Load/generate regular config *.txt* files for command documentation and user customisation.

My apologies for not suggesting all this in the first place.

**Comment by Danesprite** [comment]
It appears there is little interest in this issue.  Adding new functionality to Dragonfly for this is unnecessary; the configuration toolkit serves this purpose well.  It is really not difficult to use in command modules.  There are also many examples demonstrating use of the toolkit.

What I'll do is add a new section to the configuration toolkit documentation on its utility for documenting grammars, fix some minor formatting problems with the output of `Config.generate_config_file()`, and then close this issue.
