### ISSUE TITLE
Clarify `Playback` documentation 

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/dragonfly#270]
When you give dictation with the proper noun like `Buffalo Bills` that's capitalized by DNS in free dictation not as a command it causes playback to fail.

In Caster we have a command called `again do`

It retrieves raw recognition history from `from dragonfly import RecognitionHistory`

- raw history
`[('hello', 'how', 'are', 'you', 'Buffalo Bills')]` 

It does postprocessing to ensure that each word is an element in a list and subtracts `again do` from the recognition index.

- postprocessed
 `['hello', 'how', 'are', 'you', 'Buffalo', 'Bills'].`

 I could lower case the output but I don't see anything of the docs to suggest that it must be lowercase.

**Comment by Danesprite** [comment]
Thanks for reporting this. I'll look into it. What stands out to me is `Buffalo Bills` being one "word" in the recognition history and two words after processing. I don't know if that's related.

**Comment by LexiconCode** [comment]
That's a good point about it being two words and that it might expect that. That should be easy enough for me to test and let you know

**Comment by LexiconCode** [comment]
Well a couple of notes here

- Recursion error can be caused by the following. The command repeats itself 71 times before trace back is produced. Not directly related to the issue but interesting to note.
```
        'buffalo bills':
            R(Playback([(["buffalo", "bills"], 0.0)])), 
```
```
Traceback (most recent call last):
  File "C:\Python2\lib\site-packages\dragonfly\engines\backend_natlink\engine.py", line 411, in results_callback
    func, words=tuple(map_word(w) for w in results.getWords(0)),
  File "C:\Python2\lib\site-packages\dragonfly\engines\backend_natlink\engine.py", line 411, in <genexpr>
    func, words=tuple(map_word(w) for w in results.getWords(0)),
  File "C:\Python2\lib\site-packages\dragonfly\engines\backend_natlink\engine.py", line 60, in map_word
    if isinstance(word, text_type):
```

- Lowercase separate words
```
'buffalo bills hello':
            R(Playback([(["buffalo", "bills"], 0.0)])),
The following text is produced `Buffalo bills` Notice the capital B.
```

- Uppercase separate words
```
'buffalo bills hello':
            R(Playback([(["Buffalo", "Bills"], 0.0)])),
```
`ERROR:action.exec:Execution failed: Playback failed: No matching rule found for words ['Buffalo', 'Bills'].`

- Uppercase single utterance
Works as expected producing  `Buffalo Bills`

```
 'buffalo bills hello':
            R(Playback([(["Buffalo Bills"], 0.0)])),  
```

- Testing out Dragon's built-in commands that have formatting like `new line`
Works as expected producing the new line of DNS is built in command.
```
        'buffalo bills hello':
            R(Playback([(["\\new-line\\new line"], 0.0)])),   
```

Conclusions
`Playback` is not limited to in some circumstances to one element per word as seen with proper pronouns nor is it limited by the extra formatting by built-in commands. Therefore maybe the documentation just needs to be updated to reflect those edge cases.

I will look into Casters postprocessing function could be fixed to just remove the `again do` without disturbing the engines expected format from history. The assumption being the history reported is always valid for dragonfly playback.

**Comment by Danesprite** [comment]
Sorry for the late response. I don't understand why DNS is picky with capitals like this. I'm happy to update the documentation.

The recursion error is expected in the case where you recognise "buffalo bills" and then mimic it again. An exception caught and displayed by Natlink is certainly better than it looping forever. 😉

**Comment by Danesprite** [comment]
I think these things should be documented in a new page for the Natlink engine back-end. The documentation for `Playback` and `Mimic` can then reference that page.

Some of the other engine back-ends also have quirky mimic behaviour, e.g. SAPI 5 sometimes fails to mimic commands for no discernible reason. I'll put together a new page for that engine as well.
