### ISSUE TITLE
docs: Related resources: remove dead link to Hawkeye Parker's repo -- add link to his grammars

### ISSUE THREAD

**Issue by haughki** [dictation-toolbox/dragonfly#272]
My dead fork and grammars. I think the grammars are worth adding to the list. I will fork and submit fix.

**Comment by haughki** [comment]
PR: https://github.com/dictation-toolbox/dragonfly/pull/273

**Comment by Danesprite** [comment]
Thanks again. Let me know if you find other issues like this :)
