### ISSUE TITLE
Can't use BasicRule directly, only as a derived class

### ISSUE THREAD

**Issue by daanzu** [dictation-toolbox/dragonfly#274]
The following way of using `BasicRule` doesn't work, because the class variable `BasicRule.element` shadows the property `ElementBase.element`, which is accessed during compilation, but is left set to `None`.

`g.add_rule(BasicRule(element=Empty(name='empty')))`

**Comment by Danesprite** [comment]
Thanks! I will fix this soon. My fault for not writing unit tests for this class!

**Comment by daanzu** [comment]
No problem. (I did think to myself "I'm surprised Dane's unit tests didn't catch this". 😉) I couldn't decide which fix would be best, so I figured I'd leave it to you.

**Comment by Danesprite** [comment]
This is all fixed now. I adapted the workaround already present for the `exported` property. Next time I'll write proper tests! 🤭
