### ISSUE TITLE
High-DPI awareness issues with Win32 monitor-related functionality

### ISSUE THREAD

**Issue by Danesprite** [dictation-toolbox/dragonfly#289]
CC @LexiconCode @wolfmanstout

There can be problems with Dragonfly's monitor-related functionality on Windows Vista and above if it is run from certain (usually older) applications whose [`DPI_AWARENESS_CONTEXT`](https://docs.microsoft.com/en-us/windows/win32/hidpi/dpi-awareness-context) value is `DPI_AWARENESS_CONTEXT_UNAWARE`. Microsoft's documentation on setting the DPI awareness for a process is [here](https://docs.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process).

This was discovered in the following issue: https://github.com/wolfmanstout/gaze-ocr/issues/1. It can be fixed by calling one of the Windows API functions for setting DPI awareness: [`SetProcessDPIAware()`](https://msdn.microsoft.com/library/windows/desktop/ms633543(v=vs.85).aspx), [`SetProcessDpiAwareness()`](https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-setprocessdpiawareness) or [`SetProcessDpiAwarenessContext()`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setprocessdpiawarenesscontext). Each of these functions can fail if the `DPI_AWARENESS_CONTEXT` value is set in the application manifest.

The following is how @wolfmanstout fixed the problem in Dragonfly (from https://github.com/dictation-toolbox/dragonfly/commit/c3a1b1e306a720e5b2e1ad3b8c5c3d4e1e30c668):

```Python
import ctypes

# Force the current process to be DPI aware. This will ensure that the
# resolution is reported properly even when DPI scaling is on. This appears to
# be set to PROCESS_SYSTEM_DPI_AWARE when running embedded in Dragon, which
# provides awareness of the DPI when the application starts, but not when it
# changes. Unfortunately, this cannot be changed (presumably it is declared in a
# manifest). When running from the command line, however, the default is
# PROCESS_DPI_UNAWARE and can be adjusted here.
ctypes.windll.shcore.SetProcessDpiAwareness(2)  # PROCESS_PER_MONITOR_DPI_AWARE

```

It should be noted that `SetProcessDpiAwareness()` is only available on Windows 8.1.

I'm not sure if an automatic fix for this problem in Dragonfly's `win32_monitor.py` file is appropriate. It might be better to have a dedicated top-level function for use directly after importing from Dragonfly. A special function would abstract away the complicated differences between and availability of the three Windows API functions mentioned above. I'm not sure when I'll get to this, though I will put together an FAQ on this issue soon and mention it in the documentation for `Win32Monitor`.

**Comment by wolfmanstout** [comment]
Thanks Dane! I have been meaning to follow up with you on this but just haven't had time. 

I can understand if you don't always want to apply this change. One of the reasons I changed it by default is that the list of monitors is automatically loaded at import time, so I wanted to avoid any inconsistency.￼

**Comment by daanzu** [comment]
I don't have much to add, other than to note that I have had the following at the top of my loader for the past many years. I can't remember how I decided on it. I only use a single monitor.

```
from ctypes import windll
windll.shcore.SetProcessDpiAwareness(1)
```

**Comment by LexiconCode** [comment]
Can someone verify DNS/DPI that indeed does work at the top and engine loader?

It works fine when executing through Python interpreter 3.8 and 2.7. However I'm unsuccessful to have it load even with the simple file `_test.py` with nothing else and it.

```python
from ctypes import windll
error_code = windll.shcore.SetProcessDpiAwareness(2)  #enable 1-1 pixel mapping
if error_code == -2147024891:
    print("Failed to set app awareness")
```

**Comment by wolfmanstout** [comment]
@Danesprite That sounds like a pretty clean fix to me.￼

**Comment by LexiconCode** [comment]
> @LexiconCode This isn't working because the dpi awareness is already set. It is either hardcoded in the application manifest or set by a previous call to `SetProcessDpiAwareness()`. It can only be set once.

I'm aware it can be only sat once. I was expecting to have to set it as described in wolfmanstout/gaze-ocr#1 which runs out of process. However I just switch to Dragon 15.6.

**Comment by Danesprite** [comment]
Okay then. So there is no problem?

I just noticed something interesting on dpi and processes that create windows:

> [...] Once a window (an HWND) has been created in your process, changing the DPI awareness mode is no longer supported. If you are setting the process-default DPI awareness mode programmatically, you must call the corresponding API before any HWNDs have been created.

-- Microsoft's documentation on [Setting default awareness programmatically](https://docs.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process#setting-default-awareness-programmatically)

**Comment by LexiconCode** [comment]
> Okay then. So there is no problem?
> 

It might mean the manifest is different between older versions of DNS/DPI and DPI 15.6. My conclusion is it still needs to be abstracted as it's needed for For at least some versions of DNS and for other backend that don't inherit High-DPI awareness.

> I just noticed something interesting on dpi and processes that create windows:
> 
> > [...] Once a window (an HWND) has been created in your process, changing the DPI awareness mode is no longer supported. If you are setting the process-default DPI awareness mode programmatically, you must call the corresponding API before any HWNDs have been created.
> 
> -- Microsoft's documentation on [Setting default awareness programmatically](https://docs.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process#setting-default-awareness-programmatically)

That's an interesting point and what are its implications? That seems to suggest that once a process is started one cannot set dpi awareness? That means it needs to be defined in the manifest in the exe so how does that work with the dragonfly CLI/launching through Python?

**Comment by daanzu** [comment]
I think dragonfly should probably have a simple method to call to set the DPI Awareness, which could be called in the example loaders and the command line loader when run on Windows.

**Comment by Danesprite** [comment]
@LexiconCode Yep, maybe the manifest is different between Dragon versions.

The implication is that one cannot set DPI awareness after the process creates a window, presumably once [`CreateWindow()`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createwindowa) is called (what they mean by this is not clear).

@daanzu Yes, this is simpler. It doesn't really need to be automatic.

**Comment by LexiconCode** [comment]
> 
> 
> I don't have much to add, other than to note that I have had the following at the top of my loader for the past many years. I can't remember how I decided on it. I only use a single monitor.
> 
> ```
> from ctypes import windll
> windll.shcore.SetProcessDpiAwareness(1)
> ```

Testing DPI in-process. Legion gives a good visual representation of SetProcessDpiAwareness issues.

Interestingly enough this is the result setting SetProcessDpiAwareness at the top of `_caster.py`.

```
if sys.platform.startswith('win'):
      from ctypes import windll
      windll.shcore.SetProcessDpiAwareness(2)
```

![image](https://user-images.githubusercontent.com/24551569/94931748-bd6eff00-048d-11eb-9766-8bad4763efa9.png)

Versus calling it in Legion main where it was originally launched through Popen separate process.
https://github.com/kendonB/Caster/blob/1bd4b992363c11ec5e457e0a539e5d48f8ccbccb/castervoice/asynch/mouse/legion.py#L233

![image](https://user-images.githubusercontent.com/24551569/94932178-530a8e80-048e-11eb-901a-4881dea2471f.png)

With the patch to dragonfly
wolfmanstout/dragonfly@c3a1b1e
![image](https://user-images.githubusercontent.com/24551569/94933263-c791fd00-048f-11eb-8eaf-d5774f4a6ba7.png)

**Comment by daanzu** [comment]
@LexiconCode Curious. Is that code snippet in `_caster.py` executed before or after the first dragonfly import (including by other files)?

**Comment by LexiconCode** [comment]
> @LexiconCode Curious. Is that code snippet in `_caster.py` executed before or after the first dragonfly import (including by other files)?

Yes the snippet in `_caster.py has been test at the very top of the file even before dragonfly is imported. No other files are loaded alongside _caster.py.

**Comment by Danesprite** [comment]
I have been trying to write the class method I mentioned, but I just cannot wrap my head around Microsoft's different APIs for this. Why they needed so many different ways of setting DPI awareness is beyond me. All I'm going to do for this issue is add an FAQ documenting this problem with some code snippets to include before importing dragonfly.

**Comment by Danesprite** [comment]
High-DPI awareness is now mentioned in the FAQ [here](https://dragonfly2.readthedocs.io/en/latest/faq.html#why-isn-t-dragonfly-code-aware-of-dpi-scaling-settings-on-windows). I am open to a PR with code changes if you guys think this is insufficient.

**Comment by LexiconCode** [comment]
My test above suggests that it may not be enough for in process DNS with the code at the top of the first loaded grammar before dragonfly.

**Comment by Danesprite** [comment]
Yes. I don't know why it is any different in the first instance at the top of `_caster.py`. If you are able to reproduce this consistently, can I ask what values are returned by `SetProcessDpiAwareness(2)` each time? Sorry I didn't ask this sooner.

**Comment by LexiconCode** [comment]
```
if sys.platform.startswith('win'):
      from ctypes import windll
      test = windll.shcore.SetProcessDpiAwareness(2)
      print(test)
```
Of the printed value `-2147024891`. Which means it did not successfully set SetProcessDpiAwareness.

**Comment by LexiconCode** [comment]
Something weird is going on I need more time to test. Either way the FAQ is a good idea.

**Comment by Danesprite** [comment]
`-2147024891` is `0x80070005` unsigned, the value for `E_ACCESSDENIED`. So, the DPI awareness was already set for the process. I'm not sure if sub-processes inherit awareness.

I'm starting to think we should just use @wolfmanstout's original patch, adjusted to catch errors if the `SetProcessDpiAwareness()` function doesn't exist. I don't think there should be any downside to that.

**Comment by LexiconCode** [comment]
> I'm starting to think we should just use @wolfmanstout's original patch, adjusted to catch errors if the `SetProcessDpiAwareness()` function doesn't exist.

That might be the way to go as the only thing that's reliable for in/out of process with anything launch through a subprocess.

**Comment by LexiconCode** [comment]
Fortunately was that actually looks promising to calculate dpi per monitor
https://stackoverflow.com/questions/50253948/query-windows-10-8-monitor-scaling-from-python-script

```
import ctypes
import win32api

PROCESS_PER_MONITOR_DPI_AWARE = 2
MDT_EFFECTIVE_DPI = 0

#print(ctypes.windll.shcore.GetScaleFactorForDevice(0))

def print_dpi():
    shcore = ctypes.windll.shcore
    monitors = win32api.EnumDisplayMonitors()
    hresult = shcore.SetProcessDpiAwareness(PROCESS_PER_MONITOR_DPI_AWARE)
    assert hresult == 0
    dpiX = ctypes.c_uint()
    dpiY = ctypes.c_uint()
    for i, monitor in enumerate(monitors):
        shcore.GetDpiForMonitor(
            monitor[0].handle,
            MDT_EFFECTIVE_DPI,
            ctypes.byref(dpiX),
            ctypes.byref(dpiY)
        )
        print(
            f"Monitor {i} (hmonitor: {monitor[0]}) = dpiX: {dpiX.value}, dpiY: {dpiY.value}"
        )


if __name__ == "__main__":
    print_dpi()

# If you do not want to set your own application as a dpi-aware per monitor, you could try launching some variant of the above code in another process using the multiprocessing module and retrieve the results.
```

**Comment by Danesprite** [comment]
@LexiconCode Thanks!
