### ISSUE TITLE
Lunix with Kaldi: "no good block received recently, so reconnecting audio"

### ISSUE THREAD

**Issue by Timoses** [dictation-toolbox/dragonfly#291]
I receive the following on Linux with Kaldi:
```
INFO:engine:streaming audio from 'default' using ALSA: 16000 sample_rate, 10 block_duration_ms, 40 latency_ms
WARNING:engine:<dragonfly.engines.backend_kaldi.audio.VADAudio object at 0x7f26b50698d0>: no good block received recently, so reconnecting audio
```

```
arecord -f S16_LE -d 10 -r 16000 -D default test.wav  
aplay test.wav
```
successfully plays back the recorded audio.

```
> arecord -L                                                                                                                                                                                              
default
    Playback/recording through the PulseAudio sound server
null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
sysdefault:CARD=PCH
    HDA Intel PCH, ALC269VB Analog
    Default Audio Device
front:CARD=PCH,DEV=0
    HDA Intel PCH, ALC269VB Analog
    Front speakers
dmix:CARD=PCH,DEV=0
    HDA Intel PCH, ALC269VB Analog
    Direct sample mixing device
dsnoop:CARD=PCH,DEV=0
    HDA Intel PCH, ALC269VB Analog
    Direct sample snooping device
hw:CARD=PCH,DEV=0
    HDA Intel PCH, ALC269VB Analog
    Direct hardware device without any conversions
plughw:CARD=PCH,DEV=0
    HDA Intel PCH, ALC269VB Analog
    Hardware device with all software conversions
```

Using `get_engine('kaldi').print_mic_list()` as documented [here](https://dragonfly2.readthedocs.io/en/latest/kaldi_engine.html) yields:
```
LISTING ALL INPUT DEVICES SUPPORTED BY PORTAUDIO
(any device numbers not shown are for output only)

  0 HDA Intel PCH: ALC269VB Analog (hw:0,0), ALSA (2 in, 0 out)
  1 sysdefault, ALSA (128 in, 0 out)
  2 pulse, ALSA (32 in, 32 out)
* 3 default, ALSA (32 in, 32 out)
```

Voice recogintion does not seem to be working.

Please let me know if more details or input are required.

**Comment by daanzu** [comment]
@Timoses Hmm. Is your system possibly overloaded?

You could try the engine parameter `audio_self_threaded=False`.

Alternatively, if you are comfortable modifying the files in the python package, I can tell you how to disable that check to see if it otherwise works. The reconnect check shouldn't generally be needed; it was added to cover special cases, and I am not aware of it causing trouble itself before.

**Comment by Timoses** [comment]
> Hmm. Is your system possibly overloaded?

Unlikely. Out of 16GB there is still 2GB free. CPU utilization is at 1.3 (nprocs = 4) and idle around 50-80%. Very little IO.

I did comment out this block: https://github.com/dictation-toolbox/dragonfly/blob/master/dragonfly/engines/backend_kaldi/audio.py#L252-L256

And it works with that modification.


Note: My setup is kind of special. I use NoMachine to connect to a Linux desktop remotely and then use the NoMachine client to forward the audio from an input device locally to the remote machine.

(I now realise that it is quite slow.. : / . But that's another issue ; ).)

**Comment by daanzu** [comment]
I will add an option to control whether the reconnect logic is enabled. @Danesprite, do you have an opinion on whether the default should have it enabled or disabled? I am unsure. It shouldn't really be needed very often, and perhaps it is more likely to cause trouble than to solve it. Or, I could make the default dependent on the OS: the only two cases I am sure are using it (myself and @mrob95) are using it on Windows I believe.

**Comment by Danesprite** [comment]
Given that this issue hasn't come up before, I would say the option should keep it enabled by default. As for the option being dependent on the OS, `sounddevice` and Port Audio are supposed to work the same on all supported systems. I don't think we should deviate from that.

**Comment by daanzu** [comment]
This has been added as the engine parameter `audio_auto_reconnect=False`.
