### ISSUE TITLE
Example of grammar for OSX

### ISSUE THREAD

**Issue by kevinsimper** [dictation-toolbox/dragonfly#3]
I tried this to get started with a simple grammer, but it does not work, because the keys are apparently different on osx than linux.

https://github.com/dwks/aenea-grammar-simple
Tried a lot of the commands and only up/down/left/right seemed to work.

Is there an example on how to send keys to OSX like tab etc.

**Comment by nirvdrum** [comment]
To avoid confusion, I'm about to close out this repository. I think you want to take your question to https://github.com/t4ngo/dragonfly.

Having said that, I think your question really is for aenea. Dragonfly works via NatLink, which is Windows-only. Aenea works as a proxy to Dragonfly to send keystrokes over an RPC channel and requires servers that can understand the aenea protocol to work properly. It sounds like a potentially bad mapping of key codes in aenea.
