### ISSUE TITLE
Number two cannot be recognized with Integer/ShortIntegerRef

### ISSUE THREAD

**Issue by wenqiangwang** [dictation-toolbox/dragonfly#307]
Don't know it is a Dragonfly issue or Kaldi engine issue, but '2' cannot be recognized with ether Integer or IntegerRef or ShortIntegerRef.

Here is my rule to repro this. Every single digit except for 2 can be recognized.

            mapping={
                "number <big_number> over": Function(lambda big_number: Text(str(big_number)).execute())
            },
            extras=[Integer(name="big_number", min=0, max=10)],

I figured out that if I just keep only one of the 'two | too | to' at the line of code below, the problem go away. Can someone please take a look? 

https://github.com/dictation-toolbox/dragonfly/blob/1108157b69e996f799cd78380930fd56bd675c36/dragonfly/language/en/number.py#L39

**Comment by Danesprite** [comment]
Hi @wenqiangwang,

Thanks for reporting this issue. I was unaware this was a problem using Kaldi. The two extra alternatives for recognising the number two were added in response to #84, where Dragon could misrecognise "two" as "too" or "to". I'll look into adjusting this so it's only done for Dragon. IIRC the test suite for the SAPI5/WSR engine back-end fails sometimes because of these alternatives.

@daanzu Have you run into this problem before?

**Comment by daanzu** [comment]
I will test some when I get a chance, but I am surprised. I think I am using that in my own grammars without any problems, and similar constructions elsewhere.

**Comment by daanzu** [comment]
@wenqiangwang Do you mean that when you speak "2", other numbers are recognized instead, or that some kind of error is raised?

**Comment by wenqiangwang** [comment]
[loader.zip](https://github.com/dictation-toolbox/dragonfly/files/5404486/loader.zip)

@daanzu @Danesprite What I mean is if I say "One" then "1" got recognized, same with 3 to 9. But when I say "Two", no thing happened. It seems like that the rule is not matched at all. But I am sure my accent with "Two" does not quite matter because if I say "Pure Two", where "pure <dictation>" is my rule, it perfectly recognized two.

Attached is the file that you could use it to repro it. The only change you might need to change is the folder of Kadie or the temp folder.

Thanks you for looking into this. And also thank you for creating this awesome software!

**Comment by wenqiangwang** [comment]
@daanzu I found another case to repro. I think it could be the same issue. I tried to have a list of alternative words for dictation, but found that 'read' cannot be recognized. I did a quick binary search and found that as long as 'read' and 'red' coexist, they both cannot be recognized. But if only one of them exists, everything is fine. Following is a repro for that. Please let me what I can help. Thanks.

    from dragonfly import *
    r = MappingRule("test", {
        "read": Text('read'),
        "red": Text('red'),
    })
    g = Grammar('test')
    g.add_rule(r)
    g.load()

**Comment by wenqiangwang** [comment]
@daanzu @Danesprite  I think I found a clue. I have set the following config to 0.1 in my loader file. With 0.1, (read | red) will fail to recognized. But if I set it to 0.5, then (read | red) work, but (two | too | to) still not work. Setting it to 1.0 makes (two | too | to) work.

expected_error_rate_threshold=0.1,  # Estimated error rate above which the recognition is ignored

It seems to me it is still a bit of confusing but depending how we defined it, it might be a bug or not. At least I think I can now work around it.

**Comment by wenqiangwang** [comment]
Here is some verbose logs. Not sure, but it seem when there are three words (e.g. two|too|to) with similar sound, the eer is 2/3 and when there are two words (e.g. read|red), then the error is 1/2.

Level 15:engine:End of phrase: eer=0.67 conf=nan [BAD], rule KaldiRule(5, keys::repeat_keys), 'number two'
Level 15:engine:End of phrase: eer=0.50 conf=nan [BAD], rule KaldiRule(4, format::FormatRule), 'say read'(

**Comment by daanzu** [comment]
@wenqiangwang Thanks for the detailed and very helpful info! With that, I think I know now the problem and what is causing it. I'll try to think of a solution that still allows for the use of expected_error_rate_threshold.

**Comment by wenqiangwang** [comment]
@daanzu That's will be great, since setting a low expected_error_rate_threshold seems generates less errors. Thanks for looking into this!
