### ISSUE TITLE
Remote / Client Actions

### ISSUE THREAD

**Issue by Timoses** [dictation-toolbox/dragonfly#310]
I am trying to figure out how to send actions to a client over the network. The motivation for this is the idea to support a [client-server architecture in caster](https://github.com/Timoses/Caster/issues/14). 

I would think that both server and client use the Dragonfly library/framework.

I see two issues involved in this endeavor:
1. Getting between Dragonfly's recognition and action workflow,
2. sending the action over the network.

### 1. Getting between Dragonfly's recognition and action workflow

["Hacking" into dragonfly's Action objects' `execute` method](https://github.com/Timoses/Caster/commit/5a24ba1df235b96e480eb95148557ff8fe87c9d0#diff-ddd1b003d2518f2cafaf0705c37592f771e81adba52da62dcf0d54ab6f8e5832R17-R18) is a first attempt of mine to jump between Dragonfly's "recognition -> action execution" workflow. This method does not require any changes on the site of Dragonfly. 

Would you see any alternative? Is it even a good idea to "support" this without changes to Dragonfly? It does feel very hacky.

Changing Dragonfly would probably allow for a better supported approach. Perhaps something like a delegated `ActionHandler` which can be set when initializing Dragonfly would be the way to go? If something like that is set then Dragonfly could send any imminent action executions to that handler with the action object. 

Would dragonfly even be able to support anything like that? Currently `get_engine` looks like the entry point for Dragonfly. There is no `Dragonfly` object which would be able to be configured. Or would you use global variables for something like that? This to me seems to be related to the question of how to initialize Dragonfly in general. For example initializing Dragonfly with an already existing engine as discussed [here](https://github.com/Timoses/Caster/issues/15).

### 2. Sending the action over the network

Again my first approach tries not to require any changes to Dragonfly. Serializing and deserializing a  dragonfly action object instance does seem promising however already poses problems with `Function` actions as the `_function` attribute/reference is not serializeable.

What could be possible is for Dragonfly to support serialization in Action objects and creating actions from such serialized data. However, other questions remain: What if the Action contains references to existing objects on the server? The client would have to somehow map these to objects on the client side. 

### Alternative ways?

Perhaps this issue poses deeper questions towards Dragonfly's architecture (?). How strongly are actions tied to recognitions? How could actions be designed to support being 'transported' over the network to designated destinations? I don't think Dragonfly should itself implement networked actions. However, offering an Action design which allows for such flexibility would be great.

Possible scenarios could be:
* Approach 1: Server does not know where actions are executed
    * Client_A: Speech recorded -> RecognitionRequest to Server
    * Server: Recognition -> RecognitionResult to Client_A
    * Client_A: "Parse" RecognitionResult to Action
        * If Action configured to be executed on Client_B
            * Action -> ( Server -> ) Client_B
            * Client_B: Execute action
        * if local: 
            * Client_A: Execute Action
* Approach 2: Server knows where to execute action
    * Client_A: Speech recorded -> RecognitionRequest to Server
    * Server: Recognition -> RecognitionResult -> "Parse" to Action
        * If Action configured to be executed on Client_A
            * Action ->  Client_A
            * Client_A: Execute action
        * If Action configured to be executed on Client_B
            * Action -> Client_B
            * Client_B: Execute Action

Very obvious components:
* Recorded Speech
* Recognition
* Action

However, how to split up an Action to potentially support above scenarios? I suppose this is where my knowledge of how Dragonfly translates Recognitions to Actions becomes very sketchy.

An aspect I deem important is performance. Approach 2 would be better as it reduces the number of stops until the action 'arrives' at the destined client.

I'll just throw this idea 'into the room' for now and hope it's interesting enough to elicit some thought process and typed (or voiced) responses : ).

**Comment by LexiconCode** [comment]
It would need to forward more than just actions though for instance monitor and so on. This concept is embodied in https://github.com/dictation-toolbox/aenea However it is very brittle and difficult to set up and even breaks randomly. So I think in concept it's useful for reference but definitely would be building from the ground up.

**Comment by Timoses** [comment]
Haven't had time to dig too much into Aenea. I'd like to spend a bit more time on looking at it.
On first sight however it seems to follow the strategy to provide proxy classes which must be used, effectively being similar to the strategy outlined above (Utilizing Actions over the network).


I have had another idea: What if we do not proxy actions but only 
1. send speech from a client to a server,
2. server returns result (either back to the client or to another client)
3. client "parses" the RecognitionResult from the server into an action.

The following must be synced from clients to server for this to work:
* Grammars (eventually only a 'dynamic' part must be transmitted to server, such as when the Grammar uses dynamic rules which can be adjusted by the client/user)
* Client's current Context

The challenging part is to keep the clients' grammar and context state synced on the server at all times. I think a polling mechanism where the server would poll the client for its current grammar and context state would take too long and lead to an unresponsive feeling.
Above would also hold true for when using Actions as the networked theme (as suggested in the initial post of this issue).

Then the server would be able to have a collection of Grammars and contexts for each client. This should be quite easy to implement as in a `ClientContext`. If the voice command is destined for Client_A then ClientContext_A is active.

Does this sound feasible?
Would Dragonfly be able to cope with this? I.e.: Having many grammars for multiple clients which are "flipped" on/off depending on which client is the target of the voice command?


Again, the synchronization of contexts and grammars from clients to server is something I'd envision to be part of Caster. What Dragonfly would have to support is "loading" an Action from a RecognitionResult (which it probably already does); though it would have to be possible to interface to that ability from Caster.

**Comment by Danesprite** [comment]
My apologies for not responding to this issue until now, @Timoses.

I would rather keep functionality like this out of Dragonfly, as it would add much more for me to maintain. You would need to have a protocol encompassing the functionality you want available on the remote client, e.g. a remote-control `Keyboard` class for using the `Key` and `Text` actions. If a user wanted *everything*, it would be quite the undertaking.

In my opinion, sending actions over the network would be best. As @LexiconCode mentioned, this is what Aenea does. Have you had time to look into it? Unfortunately, it only works with Python 2.7 at the moment.

We can discuss this in further detail here, if you like. I will close the issue now though.

**Comment by Danesprite** [comment]
@Timoses I don't think it is quite what you wanted, but I would be willing to make remote interaction easier for remote X11 systems, e.g. interaction via [OpenSSH X11 Forwarding](https://man.openbsd.org/ssh#X11_FORWARDING). This would be like locally using Dragonfly on the system running X11.

Unless I am missing something rather obvious, Dragonfly's X11 integration should be able to support this, even, with a bit of work, from Windows.
