### ISSUE TITLE
Support for Fn key.

### ISSUE THREAD

**Issue by Treshank** [dictation-toolbox/dragonfly#335]
I can't seem to be able to find documentation on the 'Fn' key. Is there support for it or any workarounds?

**Comment by Danesprite** [comment]
The <kbd>Fn</kbd> key does not typically send events to the operating system when you press it. Rather, it modifies the key event(s) sent when you press other keys while holding it. Notice that [Microsoft's list of Virtual-Key Codes for Windows](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes) does not include this key.

Anyhow, what is your use case? It is possible to use Dragonfly to simulate any key you can press by using <kbd>Fn</kbd> on your keyboard, e.g. the volume up key:

```Python
Key("volumeup")
```

**Comment by Treshank** [comment]
Alot of keyboards now come with shortcuts mapped to it. So I was wondering if I could also map Fn key shortcuts.

**Comment by Danesprite** [comment]
Yes, you should be able to do that. Which ones did you want to map?

**Comment by Treshank** [comment]
The Fn and some function key (f1-f12), Fn+Del, Fn+End, Fn+(1,2 3)
many are there

**Comment by Danesprite** [comment]
All right. Just so we are on the same page, you want to have voice commands that simulate these key combinations? E.g. you speak "volume up" and the appropriate `Fn + <key>` combo is pressed. Assuming there is a volume up combo.

**Comment by Treshank** [comment]
Not volume up specifically, cus it's already there, but yeah something like that

**Comment by Danesprite** [comment]
Ah, well if you want to map Windows keys not defined in Dragonfly, you could do something like this:

```Python
from dragonfly import Key, MappingRule
from dragonfly.actions.typeables import Typeable, typeables

# Add custom Typeables for a few extra Windows keys.
# Virtual-Key Codes from this page: https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
typeables["startapp1"] = Typeable(code=0xB6, name="startapp1")
typeables["startapp2"] = Typeable(code=0xB7, name="startapp2")
typeables["startmail"] = Typeable(code=0xB4, name="startmail")
typeables["browserhome"] = Typeable(code=0xAC, name="browserhome")

class MyRule(MappingRule):
    mapping = {
        "app one | my computer": Key("startapp1"),
        "app two | calculator": Key("startapp2"),
        "mail app": Key("startmail"),
        "browser app | browser homepage": Key("browserhome"),
    }

```

I could add some of these in the next version if you like.

**Comment by Danesprite** [comment]
I'm closing this issue as it is not possible to support the <kbd>Fn</kbd> key in Dragonfly.

Let me know if you would like me to add additional keys as per my last comment.
