### ISSUE TITLE
Incorrect documentation for installation (with Natlink)

### ISSUE THREAD

**Issue by altosaar** [dictation-toolbox/dragonfly#341]
The docs (https://dragonfly2.readthedocs.io/en/latest/natlink_engine.html#refnatlinkengine) state:

```
Natlink automatically loads macro files from a predefined directory. Common locations are:

C:\Program Files\NatLink\MacroSystem
My Documents\Natlink

At least one of these should be present after installing Natlink. 
```

However, after installing natlink following the instructions at https://github.com/dictation-toolbox/natlink - there is no MacroSystem directory. 

After running `start_natlinkconfig.exe`, I had to enable the user directory (I put it in Dropbox).

![image](https://user-images.githubusercontent.com/5317244/118828560-60448400-b88b-11eb-8820-9bd5c0df2348.png)

This is the info tab:

![image](https://user-images.githubusercontent.com/5317244/118828616-6aff1900-b88b-11eb-8699-59d1de1f4248.png)

Do you know how to create or find the MacroSystem directory? 

(It could be helpful to update the install instructions with this info. Thank you!)

**Comment by Danesprite** [comment]
Thank you for reporting this. This is a mistake. The typical path for the MacroSystem directory — `C:\NatLink\NatLink\MacroSystem` — is missing from this list. That directory is common using the stable versions of Natlink that require Python 2.7. It seems this is done differently using the (unstable) development version that works with Python 3.

Nevertheless, setting the Natlink User Directory was the right thing to do. I will update the Natlink engine documentation page to include "C:\NatLink\NatLink\MacroSystem" and a few other things that are missing.

**Comment by Danesprite** [comment]
I've updated the Natlink engine documentation page. I think it is clearer now. Do you see anything else that should be added in?

**Comment by altosaar** [comment]
Thanks so much @Danesprite ! 

Would a 'quickstart' guide make sense to add as a top level heading in https://dragonfly2.readthedocs.io/en/latest/? It could simply be a few steps to reproduce a minimal working example with the least amount of effort, a few commands to help verify that everything is working properly. 

Context: there are so many moving parts here and I still can't get natlink/dragonfly to work with Dragon 15. Being able to know what to test to verify a minimal working example would be super helpful.

(I've spent a few hours on the phone with Nuance support over the past few days reinstalling Dragon. Not sure whether it's Dragon itself breaking things or my attempts at configuring natlink/dragonfly, and I'm not sure how to test these things given it's my first time trying to use this!)

**Comment by LexiconCode** [comment]
I wouldn't mind connecting remotely over TeamViewer or something similar if you would think that would be helpful.

**Comment by LexiconCode** [comment]
Okay go ahead and get a hold of me through [gitter](https://gitter.im/dictation-toolbox/dragonfly) via private chat. Once you enter the chat you can click on my icon and it gives you the option for private chat.

**Comment by Danesprite** [comment]
@altosaar Glad I could help!

A 'quickstart' guide would very much depend on the engine back-end you're using. So we have separate pages for each engine. It is more involved with Natlink than the others. But, clearly, the page for it could be better. There are Natlink install instructions for the stable version (4.2), along with a video guide, [here](https://qh.antenna.nl/unimacro/installation/installationstableversionpython2.html). I'll include a link for this on the page.

Sorry you've had trouble getting all this working.

**Comment by Danesprite** [comment]
I've added the link for [this page](https://qh.antenna.nl/unimacro/installation/index.html) instead, which is the page "above" it in the sitemap.

**Comment by altosaar** [comment]
Thanks @Danesprite and @LexiconCode ! Just submitted a minimal working example with @LexiconCode 's template: https://github.com/dictation-toolbox/dragonfly/compare/master...altosaar:patch-1 

Let me know if that looks OK!

**Comment by LexiconCode** [comment]
> Let me know if that looks OK!

Looks great and to the point!
