### ISSUE TITLE
Window class implementations for other platforms

### ISSUE THREAD

**Issue by Danesprite** [dictation-toolbox/dragonfly#35]
Re: cross-platform support (issue #8).

Dragonfly's [Window class](https://github.com/Danesprite/dragonfly/blob/master/dragonfly/windows/window.py) could be abstracted somewhat to have implementations for Windows, X11 and MacOS. `from dragonfly import Window` should import the implementation for the current platform. As with the cross-platform `Clipboard` class, implementations for other platforms can be in the `dragonfly.util` sub-package.

If this is done in dragonfly instead of in external projects such as Aenea, engine implementations can get the window context for supported platforms more easily. This should also make it relatively easy to implement dragonfly's `WaitWindow`, `FocusWindow`, `StartApp` and `BringApp` actions for supported platforms as they mostly just use the `Window` class in some way.

I think that [python-xlib](https://github.com/python-xlib/python-xlib) can be used to implement the Window class for X11. xdotool or xdo can be used instead if I'm wrong about that.

@wolfmanstout you may be interested in this for your Google engine.

**Comment by wolfmanstout** [comment]
Agreed, this would be very useful, and is something I bumped into with my Google engine. I would say more broadly that Dragonfly needs a cross-platform interface for everything including what is described here, plus mouse and keyboard input, and also accessibility-based control of applications. Basically, all interactions to and from the operating system UI. In principle, this is functionality that is not tied to speech recognition, so it could be in a separate project from Dragonfly, but it cannot be a project which depends on Dragonfly (e.g. Aenea). For now, to keep things simple, I think it makes sense to keep this functionality contained within Dragonfly, but to put it in modules such that if we ever wanted to spin it out, we could easily do so. And I think it certainly makes sense to build on top of other open source projects where available.

**Comment by Danesprite** [comment]
I've done a little research on this for MacOS. As I understand it, the accessibility APIs for MacOS are difficult to use from Python without knowledge of Objective-C. I was thinking that it would be easier to write a Swift command-line program using [Swindler](https://github.com/tmandry/Swindler) and/or [AXSwift](https://github.com/tmandry/AXSwift) and use it from Python as a subprocess like xdotool.

This is also kind of related to #46.

**Comment by Danesprite** [comment]
The macOS `Window` class has now been implemented and will be released in the next version of dragonfly2. Wayland is the only other desktop platform that comes to mind, but I don't think we can implement a `Window` class for it.

**Comment by Danesprite** [comment]
I'm closing this now that `Window` classes for X11 (Linux) and macOS are now implemented.
