### ISSUE TITLE
Kaldi back-end invokes AGPL license

### ISSUE THREAD

**Issue by matthewmcintire** [dictation-toolbox/dragonfly#355]
Could a note be made somewhere more prominently in the documentation that when using the Kaldi back end, the AGPL license from kaldi_active_grammar subsumes the LGPL license from dragonfly? AGPL is significantly more restrictive.

**Comment by Danesprite** [comment]
Certainly.  I can add the license name alongside Kaldi where the engine back-ends are listed, e.g. in the *README* file's *Introduction* section.  I'll do the same for the CMU Sphinx back-end, which is also licensed differently.

David Zurow (@daanzu) has indicated on the KaldiAG project page [here](https://github.com/daanzu/kaldi-active-grammar#license) that he is willing to be flexible for those who find the license problematic.

Sorry for the late reply.

**Comment by Danesprite** [comment]
My aside on the license for CMU Sphinx is not so accurate.  That license is permissive and appears essentially the same as the 2-clause BSD license.
