### ISSUE TITLE
Launching sapi5 win32com has no attribute CLSIDToClassMap

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/dragonfly#359]
When launching sapi5 via cli I get;
```
WARNING:engine:Exception while initializing sapi5 engine: module 'win32com.gen_py.C866CA3A-32F7-11D2-9602-00C04F8EE628x0x5x4' has no attribute 'CLSIDToClassMap'
ERROR:command:Exception while initializing sapi5 engine: module 'win32com.gen_py.C866CA3A-32F7-11D2-9602-00C04F8EE628x0x5x4' has no attribute 'CLSIDToClassMap
```

Workaround:
- ` Remove-Item -path $env:LOCALAPPDATA\Temp\gen_py -recurse`
https://gist.github.com/rdapaz/63590adb94a46039ca4a10994dff9dbe

**Comment by Danesprite** [comment]
Thanks for opening an issue on this problem.  I've been aware of it for some time and came up with a similar workaround.  Unless I am missing something, I'd say this is an external bug with pywin32.

**Comment by Danesprite** [comment]
I don't even get this error on my system any more.  Maybe it's fixed?

Or maybe it only happens when pywin32 is installed via pip?  If I recall correctly, the installer version performs some extra steps, related to win32com, that can't feasibly be done via pip.

**Comment by LexiconCode** [comment]
Yeah you can feel free to close as I have not experienced it in a while.

**Comment by Danesprite** [comment]
All right then.  We can always re-open it later if necessary.

**Comment by NigelHiggs30** [comment]
I am now experiencing the problem.
