### ISSUE TITLE
python publish in wrong folder - github workflows won't run.

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/dragonfly#382]
probably my error in https://github.com/dictation-toolbox/dragonfly/pull/380, i must have put the file in the wrong folder.  
python_publish.yml is in the root folder;  it should be in a .github/workflows folder.  It will need to be moved prior to using the workflow (ie using the draft a release feature of github to run it).  There is no harm in leaving the file where it is until you want to use the workflow features.

**Comment by drmfinlay** [comment]
Thanks, Doug.  I'll put the file in the right folder.
