### ISSUE TITLE
Dragon 16 bug affecting grammar rule deactivations and contexts

### ISSUE THREAD

**Issue by drmfinlay** [dictation-toolbox/dragonfly#385]
There is a bug with Dragon 16 where deactivating one rule of a grammar can deactivate all the rules of that grammar.  The relevant NatLink issue is dictation-toolbox/natlink#179.  Unfortunately, I don't have Dragon 16 and so cannot test if Dragonfly is affected.  I suspect it is, but it hasn't been noticed yet.

Dragonfly users typically use grammar-wide contexts, meaning that grammar rules are typically either all activated or all deactivated depending on the context.  So most users won't notice this issue.  Users who utilise rule-specific contexts will probably be affected, however.  It should be possible to add in a workaround in the next version, although this really should be fixed by Nuance.

One way to test if this issue is present is by trying to use Dragonfly's [_fruit_toggle.py](https://github.com/dictation-toolbox/dragonfly/blob/master/dragonfly/examples/_fruit_toggle.py) example command module with lines 38 and 39, and lines 46 and 47, swapped.

**Comment by drmfinlay** [comment]
This issue apparently affects Dragon 15, too, but I haven't experienced it.

**Comment by quintijn** [comment]
Dane, this issue was NOT seen before in Dragon 15. Let us hope it does not show up again in other circumstances!! I think this can be closed for now...

**Comment by drmfinlay** [comment]
Hi Quintijn,

I agree with you, I haven't seen it in Dragon 15 either.  I was only relaying what Mark Lillibridge said on Gitter about this [here](https://matrix.to/#/!dZjTeWkzjVncYXWhNg:gitter.im/$Wk29yUqi-Lh_sy5AKkw7sK9cqAMIeBc2nh2JucJVkS4?via=gitter.im&via=matrix.org).

I'm fine with closing the issue for the moment.  I'll reopen it if I get a report from a user.
