### ISSUE TITLE
Grammars with Sapi5SharedEngine containing rules with <n> do not load.

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/dragonfly#41]
This was initially discussed on Gitter, summarized here and discovered during testing synkarius/caster#305.

Mapping like '[use] function <n\> [<text\>]' with rules containing `<n>` don't load on windows speech recognition.  Dragonfly's `get_engine` method uses `Sapi5SharedEngine`. WSR module loader uses `Sapi5InProcEngine` which loads `sample.py` loads properly.  

[t4ngo/dragonfly#3](https://github.com/t4ngo/dragonfly/issues/3) appears to be the rational behind having two engine classes for it. Sapi5InProcEngine doesn't seem to need you to start WSR at all, but doesn't have any UI components.

To replicate `E:\NatLink\NatLink\MacroSystem> python .\sample.py`
[sample.zip](https://github.com/Danesprite/dragonfly/files/2531662/sample.zip)
```
 Traceback (most recent call last):
  File ".\sample.py", line 81, in <module>
    grammar.load()
  File "C:\Python27\lib\site-packages\dragonfly\grammar\grammar_base.py", line 338, in load
    self._engine.load_grammar(self)
  File "C:\Python27\lib\site-packages\dragonfly\engines\base\engine.py", line 136, in load_grammar
    wrapper = self._load_grammar(grammar)
  File "C:\Python27\lib\site-packages\dragonfly\engines\backend_sapi5\engine.py", line 124, in _load_grammar
    handle.CmdSetRuleState(rule.name, constants.SGDSActive)
  File "C:\Python27\lib\site-packages\win32com\gen_py\C866CA3A-32F7-11D2-9602-00C04F8EE628x0x5x4\ISpeechRecoGrammar.py", line 67, in CmdSetRuleState
    , State)
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147200940), None)
```

**Comment by Danesprite** [comment]
Thanks for the issue. I'm wondering if this is a problem with the engine's compiler. Perhaps the integer rules aren't being compiled correctly?

**Comment by Danesprite** [comment]
So there are some debug options that can be enabled for dragonfly's Sapi5 compiler [here](https://github.com/Danesprite/dragonfly/blob/master/dragonfly/engines/backend_sapi5/compiler.py#L46) and [here](https://github.com/Danesprite/dragonfly/blob/master/dragonfly/engines/backend_sapi5/compiler.py#L105). Maybe Microsoft has some documentation on error codes for WSR?

**Comment by LexiconCode** [comment]
With a little more testing from other sources I'd like to confirm but I believe the issue has been fixed by https://github.com/Danesprite/dragonfly/issues/25

**Comment by LexiconCode** [comment]
That makes sense. In addition I should probably add an upstream label as well.
