### ISSUE TITLE
Discuss moving Dragonfly into dictation-toolbox

### ISSUE THREAD

**Issue by calmofthestorm** [dictation-toolbox/dragonfly#48]
Danesprite invited me to discuss this in https://github.com/dictation-toolbox/dictation-toolbox/pull/1#issuecomment-447642069; this issue is to discuss whether it would make sense to move Dragonfly into dictation-toolbox. We're currently working with Caster in https://github.com/synkarius/caster/issues/321 to do the same.

dictation-toolbox is intended to be a lightweight organization for collecting projects related to voice coding and computer use, plus a contingency plan in the event that all maintainers of a project leave. Individual projects would still remain independent in terms of governance, community management, etc. See https://github.com/dictation-toolbox/dictation-toolbox/pull/1 for the work on drafting this up, and please feel free to weigh in.

**Comment by Danesprite** [comment]
Thanks for opening this issue :)

I noticed that GitHub's documentation on [repository transfers](https://help.github.com/articles/about-repository-transfers/) indicates that the process is pretty painless. Links will redirect to the transferred repository, which includes links used in Git remotes.

To extend the contingency plan mentioned for dictation-toolbox, I think it would be good if there were others with maintainer-level access to the external projects for dragonfly2: Read the Docs and PyPI.

**Comment by calmofthestorm** [comment]
Good point on the external projects. I'll defer to how you want to handle that -- we could cross grant to the public admins of the org, or do something else.

**Comment by Danesprite** [comment]
Granting access to admins of the org sounds good to me.

**Comment by LexiconCode** [comment]
Well as everyone already probably knows I'm in support of this as well :)

**Comment by wolfmanstout** [comment]
:+1:

**Comment by calmofthestorm** [comment]
If no one objects by Jan 2, and we're all on board with this, I think the next step is for me to add the admins of Dragonfly (just @Danesprite ? Or others too) to dictation-toolbox admins, and then we can reach out to Github to do the repository transfer. I assume you'll want to initiate that request, but of course I am happy to be a point of contact on dictation-toolbox side.

Anything else I should do as part of that?

Awesome to see the community banding together on this; and especially taking steps to avoid needing to create dragonfly3:-)

**Comment by Danesprite** [comment]
Sounds good. I'll initiate the request when the time comes. @LexiconCode would be an admin too, although he'll already be part of the organisation from Caster's migration.

There is something else you can do regarding the external projects. I can send invites to other RTD and PyPI users. When convenient, could you please create accounts on each site and send me the usernames? No rush.

> Awesome to see the community banding together on this; and especially taking steps to avoid needing to create dragonfly3:-)

Indeed :-)

**Comment by calmofthestorm** [comment]
Ok, I have invited @Danesprite and @LexiconCode to be admins of dictation-toolbox, and am ready to accept the transfer once initiated within 24h. I'll be home all week so should be able to reply within the window.

**Comment by calmofthestorm** [comment]
I registered as calmofthestorm on both readthedocs.org and pypi.

**Comment by Danesprite** [comment]
Thanks Alex! I have accepted your invitation to dictation-toolbox and have added you as an additional maintainer on readthedocs.org and pypi.

I was going to initiate the transfer request, although apparently as a member I was able to transfer the repository myself. I will update the repository hyperlinks to dictation-toolbox/dragonfly shortly.
