### ISSUE TITLE
Dragonfly's unit and doc tests are broken

### ISSUE THREAD

**Issue by Danesprite** [dictation-toolbox/dragonfly#52]
The tests don't run properly at the moment (at least for me) because of relative importing. I'm working on fixing this. I'd like to make the test suites work properly so they can be run through Travis CI.

Various tests in [test_engine_text.py](https://github.com/Danesprite/dragonfly/blob/master/dragonfly/test/test_engine_text.py) are duplicates or should be moved elsewhere so that they apply to all engines. The Pocket Sphinx engine tests need to be adjusted too, but I'll do that with the rework I've been planning for that engine.

**Comment by wolfmanstout** [comment]
I hope this wasn't my changes, sorry if it was (I think I had some relative imports). I ran tests against my own test suite manually, but not against the whole thing. Should I be following these instructions before sending out pull requests, or is there another recommended (i.e. faster) method? 
https://dragonfly2.readthedocs.io/en/latest/tests.html
