### ISSUE TITLE
Recognition history through JSON-RPC

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/dragonfly#80]
Currently we can pull grammars from the supported engine system through JSON-RPC. It would be useful to have the ability to pull recognition history as well. 

Commands: All recognized commands
Free dictation: All recognized dictations
A message for Dictations that are not recognized by the engine. DNS (say that again)

**Comment by Danesprite** [comment]
That's a good idea. It's not too difficult to do it either. Something like this:

```Python
from dragonfly import RecognitionHistory, RPCServer

server = RPCServer()
server.start()

history = RecognitionHistory()
history.register()

@server.add_method
def get_recognition_history():
    return list(history)

```

You could then get the history with `curl`:

```Shell
curl --data-binary '{"jsonrpc":"2.0","id": "0","method": "get_recognition_history","params": ["<security-token>"]}' -H 'content-type:text/plain;' http://127.0.0.1:50051

```
You would need to use the server's security token for requests, a custom history class for recognition failures and call `history.unregister()` and `server.stop()` somewhere eventually.

The RPC function could also have a history limit parameter.

The main problem with adding it as a builtin is that it requires storing the history as a global in *methods.py*.

**Comment by LexiconCode** [comment]
This looks excellent and I will test this weekend.

However one question does come to mind. Is there way the server can push updates to the client? The current implementation has the client of requesting x (default 10) recognition history. For most usage scenarios for this type of feature we want to stream updates to the client as they are recognized by the engine. Why not have the server push updates as command/dictation are recognized.
