### ISSUE TITLE
macron not printing

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/dragonfly#83]
I get the following error when trying to print the macron "a" in ngā mihi. 

```
Function(maori_words): 'ascii' codec can't decode byte 0xc4 in position 2: ordinal not in range(128)`
```
My function is:
```python
def maori_words(big, word):
    if big:
        word = word.title()
    Text(str(word)).execute()
```
Is dragonfly able to handle this situation when passing a UTF-8 character through `Function` and `Text`? If so, help!

**Comment by Danesprite** [comment]
Dragonfly can type "ngā mihi" through `Text`. The problem you're having here is that you should be using `unicode` instead of `str`:

```Python
def maori_words(big, word):
    word = unicode(word)
    if big:
        word = word.title()
    Text(word).execute()

```

You may also need to change the `unicode_keyboard` setting in your configuration file for this to work. See dragonfly's documentation on [Windows Unicode keyboard support](https://dragonfly2.readthedocs.io/en/latest/actions.html#windows-unicode-keyboard-support). You either need to restart Dragon for the change to take effect or manually call the `load_configuration` function in `dragonfly.actions.action_text`.

The `Key` action cannot currently type these characters.

**Comment by kendonB** [comment]
Thanks so much! I will try this out and reopen if needed.

**Comment by kendonB** [comment]
I'm still seeing an error here. It's probably some small thing I missed but I can't figure it out.

I have changed `unicode_keyboard = True` in the config file, and added that change to my function. My full caster file is:

```python
# -*- coding: UTF-8 -*-
'''
Created on May 20, 2019

@author: Kendon Bell
'''
from dragonfly import Function, Choice

from castervoice.lib import control
from castervoice.lib.actions import Key, Text
from castervoice.lib.dfplus.merge.mergerule import MergeRule
from castervoice.lib.dfplus.state.short import R

def maori_words(big, word):
    word = unicode(word)
    if big:
        word = word.capitalize()
    Text(word).execute()

class Maori(MergeRule):
    pronunciation = "maori" 

    mapping = {
        "maori word [<big>] <word>":
            R(Function(maori_words, extra={"big", "word"}) + Text(" "),
              rdescript="Maori: Insert word"),
    }

    extras = [
        Choice("big", 
        {
            "big": True,
        }),
        Choice("word", {
            "kyah order": "kia ora",
            "ngaa mihhy": "ngā mihi",
        }),
    ]
    defaults = {
        "big": False,
    }

control.nexus().merger.add_global_rule(Maori())
```
And I get this error:
```
action: Exception from function maori_words:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\dragonfly\actions\action_function.py", line 136, in _execute
    self._function(**arguments)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ccr\maori\maori.py", line 15, in maori_words
    word = unicode(word)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 2: ordinal not in range(128)
action.exec: Execution failed: Function(maori_words): 'ascii' codec can't decode byte 0xc4 in position 2: ordinal not in range(128)
```

**Comment by kendonB** [comment]
I had some "rubber duck"-style success. I just needed to add `u` as a prefix to the string `u"ngā mihi"`. I have changed it up there for Googlers.

**Comment by Danesprite** [comment]
Yep, using `u"ngā mihi"` works. I suggested `unicode(word)` because I assumed `word` was referencing a `Dictation` element rather than a `Choice`. You could also use `unicode(word, encoding='utf-8')`.
