### ISSUE TITLE
Accept "too" and "to" as equivalent to "two" for English Integers

### ISSUE THREAD

**Issue by lexxish** [dictation-toolbox/dragonfly#84]
Sometimes "too" is interpreted instead of "two" when using an Integer or Short Integer which causes failure to recognize the spec as matching.

**Comment by jcaw** [comment]
@lexxish - is this resolved?

**Comment by lexxish** [comment]
@jcaw yes I've tested it and it works. @Danesprite can you please close.

**Comment by Danesprite** [comment]
I am assuming this was an issue with Dragon specifically. Please correct me if I'm wrong @lexxish.

**Comment by lexxish** [comment]
> I am assuming this was an issue with Dragon specifically. Please correct me if I'm wrong @lexxish.

I don't know if it was specific to dragon naturally speaking but I was using dragon naturally speaking when I saw this issue

**Comment by Danesprite** [comment]
Okay, thanks. I'd say it's a safe assumption then.
