### ISSUE TITLE
`FocusWindow` sometimes fails.

### ISSUE THREAD

**Issue by jcaw** [dictation-toolbox/dragonfly#86]
The method used by `FocusWindow` sometimes fails. I'm not sure why this happens. 

When it fails, it produces an error. A fallback I've used in the past is minimising, then restoring the target window. Here's the relevant method:

```python
import win32gui
import win32con

def focus_window_fallback(hwnd):
    """Fallback for focussing a window when other methods fail. 

    This method will minimise then maximise the target window. Doing 
    this produces a jarring transition animation, so use only as a 
    fallback. 

    :param hwnd: the handle of the window you want to focus.

    """
    win32gui.ShowWindow(hwnd, win32con.SW_MINIMIZE)
    win32gui.ShowWindow(hwnd, win32con.SW_RESTORE)
```

Discussing on Gitter, it seems like it would be a good idea to add this as a fallback when the primary method fails. I'm happy to integrate it if everyone approves.

**Comment by jcaw** [comment]
Implemented this patch, and it looks like it isn't foolproof.

I initially developed this to swap between sub-windows in Stata. It seems like the patch only works if the focussed window belongs to the same process as the target window.

It looks like this issue has popped up before, and been solved by `pywinauto`, which looks like a pretty robust system. Would people be comfortable adding `pywinauto` as a dependency to `dragonfly`?

https://github.com/pywinauto/pywinauto/issues/117

**Comment by Danesprite** [comment]
Thanks for looking into this! I would not be opposed to requiring `pywinauto` on Windows. We could also just use their code in the `Window` class with attribution if that is easier.

**Comment by jcaw** [comment]
Yep, I'm thinking it offloads the hard UI interaction work onto a library dedicated to it.

**Comment by Danesprite** [comment]
Yep, that sounds like a good idea to me.

**Comment by alexboche** [comment]
just wanted to mention the Unimacro stuff for switching windows which is called the task grammar. code [here](https://paste.gg/p/anonymous/5a08115a0a044e468554979cb3477803). I like the command "task give name <dictation>" which can be followed by "task <name>" . gives temporary names to Windows. see the function rule_taskaction (366) if this is of any interest.

**Comment by daanzu** [comment]
FWIW, a simple temporary mitigation: for me, a command that does alt-tab usually fixes it (until the next time).

**Comment by Danesprite** [comment]
@alexboche Thanks for mentioning the Unimacro code for this. Looks like Quintijn has also discovered that window switching helps ([see natlinkutilsqh.py line 1549](https://sourceforge.net/p/unimacro/code/HEAD/tree/trunk/natlinkutilsqh.py#l1549)). He also checks `win32gui.IsWindow(handle)` and `win32gui.IsIconic(handle)` before calling `win32gui.SetForegroundWindow(handle)`.

@jcaw Have you had any luck getting pywinauto to work within a natlink command module?

**Comment by jcaw** [comment]
Haven't tried from NatLink yet - I've only tested in toy scenarios. I'm still running an older version of dragonfly, the newer versions break my chaining system. I'm holding off on migrating until draconity is a viable backend, and probably until Caster is unfrozen after the rewrite.

**Comment by jcaw** [comment]
>Thanks for mentioning the Unimacro code for this. Looks like Quintijn has also discovered that window switching helps (see natlinkutilsqh.py line 1549). 

Have a look at the `pywinauto` [commit](https://github.com/moden-py/pywinauto/commit/5e4735b53e2aff614361567eca8045c92275fbbc#diff-15d5f7fcb9b44b6d434fd5703b7da29aR1580) they used to fix the issue - the threading logic is interesting. It seems to be an issue with thread permissions. Programmatic window switching _seems_ to put the thread permissions into a weird state, I guess alt+tabbing resets them to normal.

**Comment by Danesprite** [comment]
Thanks! That threading logic is interesting. I was not aware of the `AttachThreadInput` function. The [documentation](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-setforegroundwindow) for `SetForegroundWindow` also sheds some light on its behaviour.

I don't use Unimacro, but it looks like Quintijn falls back on giving natspeak.exe the last input event via the DragonBar hotkey. That approach isn't portable to other engines of course.

Probably should be another issue, but what specifically breaks for you in newer versions of dragonfly? Is Draconity ready for that? I haven't really looked into it yet.

**Comment by Danesprite** [comment]
@jcaw I've just been having a look into this again. The threading logic you linked to doesn't fix the problem for me on Windows 7. In fact, `pywinauto` now just moves/clicks the mouse before calling `SetForegroundWindow()`. I guess this satisfies the following condition (see [SetForegroundWindow remarks](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setforegroundwindow#remarks)):

> * The process received the last input event.

See https://github.com/pywinauto/pywinauto/issues/270 for more on this.

I have it working by pressing the control key instead. I will add my changes shortly.

The function doesn't work if the current window is running in elevated mode, which is to be expected really, but is not mentioned in the documentation.

**Comment by Danesprite** [comment]
This should be fixed now. There are some cases where it can still fail:

1. If the current window is running in elevated mode / as administrator. There is no documentation on this limitation that I can find, but we can assume it has been put in place for security reasons.
2. If the current window is the metro app menu or a [UWP app](https://en.wikipedia.org/wiki/Universal_Windows_Platform_apps). This is easy enough to work around by just manually focusing a normal window with the mouse or alt tab.
