### ISSUE TITLE
Functionality to remap integer phrasings?

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/dragonfly#87]
Caster currently re-implements the integer class from dragonfly to allow for changing the phrasing of single integers to "one", "torque", "traio", "fairn", "faif", "six", "seven", "eigen", "nine". It would be nice to be able to allow a user to do something like this directly with the dragonfly classes. Would it be feasible to allow a user to pass a list to replace the phrasings in īnt_1_9 to their choosing? https://github.com/dictation-toolbox/dragonfly/blob/c8ebb79198fdbba719790236cb830e29701ec4a7/dragonfly/language/en/number.py#L37-L46

Perhaps a simple way to do it is to allow the user to put their own "language" file in the `.dragonfly2-speech` folder, which would replace the `en/number.py` etc file.

**Comment by Danesprite** [comment]
I think adding configuration for this under `.dragonfly2-speech` could work. When you think about it, the `language` sub-package essentially defines language-specific grammar rules. The configuration toolkit (`dragonfly.config`) could probably be used somehow.

Would it only be these digits? Things could get quite complicated if we wanted to expose configuration of larger numbers. The approach should also work with the other supported languages.

**Comment by mrob95** [comment]
It is reasonably simple to make alterations in a subclass with something like:
```
class ShortIntegerRefNo8(RuleWrap):
    def __init__(self, name, min, max, default=None):
        content = language.ShortIntegerContent
        content.builders[1] = MapIntBuilder({
                                 "one"  : 1,
                                 "two"  : 2,
                                 "three": 3,
                                 "four" : 4,
                                 "five" : 5,
                                 "six"  : 6,
                                 "seven": 7,
                                 "eigen": 8,
                                 "nine" : 9,
                               })

        element = Integer(None, min, max, content=content)
        RuleWrap.__init__(self, name, element, default=default)
```

Does it need to be simpler than this?

**Comment by kendonB** [comment]
@mrob95 that approach is quite easy, yes. I will close

**Comment by Danesprite** [comment]
@mrob95 You're right, this is simple enough. Caster should probably do it this way. Thanks :+1:
