### ISSUE TITLE
Build error in backend_sapi5/engine.py

### ISSUE THREAD

**Issue by TonyWhitley** [dictation-toolbox/dragonfly#99]
Two problems when I ran wsr_module_loader_plus.py
1.   _File ".....env\lib\site-packages\dragonfly\engines\backend_sapi5\engine.py", line 336, in recognize_forever
    WinEventProcType = WINFUNCTYPE(None, HANDLE, DWORD, HWND, LONG,
NameError: name 'WINFUNCTYPE' is not defined_

which I fixed by moving the import of WINFUNCTYPE in that file

    from ctypes import windll, WinError
    from ctypes.wintypes import DWORD, HANDLE, HWND, LONG, WINFUNCTYPE

to

    from ctypes import windll, WinError, WINFUNCTYPE
    from _ctypes.wintypes_ import DWORD, HANDLE, HWND, LONG

2.    I had to correct the file name in main()
```
    except NameError:
        # The "__file__" name is not always available, for example
        # when this module is run from PythonWin.  In this case we
        # simply use the current working directory.
        path = os.getcwd()
        __file__ = os.path.join(path, "wsr_module_loader_plus.py")
```
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]

**Comment by Danesprite** [comment]
Thanks for reporting these errors and your solutions. They are fixed on master now. I should be releasing version 0.16.0 this weekend, which will include these fixes.

Please let me know if you come across other issues with SAPI5.
